### ISSUE TITLE
multiple characters with copmose keys

### ISSUE THREAD

**Issue by Riamse** [ibus/ibus#1819]
Importing from https://code.google.com/p/ibus/issues/detail?id=1728

It's still not actually fixed. See the final comment: "Contrary to src/ibuscomposetable.c:123, GTK supports outputting multiple characters. This should not have been marked as fixed."

**Comment by fujiwarat** [comment]
I think your issue and #1744 is different and it should be filed separatedly.
To fix your problem, GtkIMContextSimple also needs to be fixed and I think the implementation is not a high priority.
Probably you could modify ibus-table-others to output multiple characters instead of compose keys.
https://github.com/mike-fabian/ibus-table-others/blob/master/tables/ipa-x-sampa.txt

**Comment by fujiwarat** [comment]
Now I think you can use IBus emoji features for the two more than equal characters since ibus 1.5.15.
E.g.
```
% gsettings get org.freedesktop.ibus.panel.emoji favorites
['🦍']
% gsettings set org.freedesktop.ibus.panel.emoji favorites "['🦍', 'foo']"
```

And you can output "foo" with Control-Shift-e and from the Favorites category.

**Comment by ilysym** [comment]
I think this is a serious limitation. It makes impossible to define combining accent mark and similar symbols in .XCompose file. I couldn't find any other way to insert such symbols with IBus, except through symbol's hex-code. This is source of constant annoyance for many Russian speakers. There is no separate accented versions of Cyrillic symbols in Unicode similar to those existing for Latin scripts.

@fujiwarat, is this the same issue as in #1982? This is a GTK issue, right? If I understand correctly, you are a GNOME developer. Could you please link relevant GTK ticket here if one exist. Or briefly describe the nature of this bug. This would provide starting point for potential contributors.
