### ISSUE TITLE
Changing IM using keyboard shorcut when candidate panel is open breaks some apps

### ISSUE THREAD

**Issue by salty-horse** [ibus/ibus#1825]
I found a weird bug when using IBus with Firefox. I'm not sure if it's a bug in IBus, Firefox, GTK, or a combination of them.

Firefox has a location bar. When you type things, it auto-completes it. It also opens a drop-down.
The steps I'm about to describe inhibit the auto-complete and the drop-down.

This happens with every IM that opens a candidate panel. I'm using English and Pinyin as an example to make things easy.

1. Click location bar (or anywhere else there's a text box in Firefox)
2. Switch to an Pinyin.
3. Type some letters, and the IBus panel will appear. Do not confirm!
4. Switch back to the English input method, using a keyboard shortcut (NOT by clicking the widget in the notification area!).

Auto-completion in the location bar (and the drop-down appearing automatically) will now be inhibited.

To have it working again, switch back to Pinyin, type some letters, and CONFIRM.

For comparison, Chrome also does auto-complete and opens a drop-down, but it is less "polite" about that, opening it while typing in Pinyin mode with the drop-down visible below the candidate panel.

**Comment by fujiwarat** [comment]
> Type some letters, and the IBus panel will appear. Do not confirm!

Maybe you mean IBus property panel. It can be disabled with ibus-setup.
1. Run ibus-setup
2. Select "Do not show" in "Show property panel" pull down menu.

> Switch back to the English input method,

I guss you mean Super+space to switch input methods.
 
It will lose the auto-completion and drop-down because the IMEs switcher window take the focus.
I think Pinyin switches Chinese and English with Space key so I think there are two solutions.
1. Use the IME's shortcut key likes pinyin space key.
2. Disable the IMEs switcher window if you switches two IMEs only:
% gsettings get org.freedesktop.ibus.general switcher-delay-time
400
% gsettings set org.freedesktop.ibus.general switcher-delay-time -1

**Comment by salty-horse** [comment]
I think we're referring to different things.

1. Not sure what the property panel is. I mean the window that pops up underneath the cursor and helps you type characters. The source code seems to call it a candidate panel.
2. Yes, Super+space.
3. I'm not sure anything else takes focus. Firefox's behavior in inhibited in that regard, but everything else work fine. I can type letters, click the mouse inside the window, etc.
4. I use more than 2 IMEs, so disabling it is not an option.

Is there something that ibus does with GTK to intercept keys or certain GUI operations of application, and perhaps it forgets to turn it off when I use Super+space while the panel is open?

Since you closed the bug, am I to assume it's not a bug in IBus? Do you think it can be fixed in Firefox (But not by implementing an inelegant solution like Chrome's)?

**Comment by fujiwarat** [comment]
>  I mean the window that pops up underneath the cursor 

I think that's IBus property panel. If you don't think so, please attach the screenshot.
% gnome-screenshot -i

> I use more than 2 IMEs, so disabling it is not an option.

OK, in that case, I think you could use Space key to switch English and Chinese in pinyin.

> Is there something that ibus does with GTK to intercept keys 

IMEs switcher window takes the input focus and the auto-commit is lost. I think it cannot be avoid in ibus and firefox would not like to keep the auto-commit off the focus.
So I think only no GUI switcher can resolve your problem.
And the pinyin shortcut key can switch the languages without GUI.

**Comment by salty-horse** [comment]
So where exactly do you see the problem? IBus? Firefox? The particular IME I'm using?

I'd like to fix it in a way that's more than a personal workaround, so any pointers would be helpful.

**Comment by fujiwarat** [comment]
I'm suggesting to use the pinyin shortcut.

**Comment by lalomartins** [comment]
We're not talking about switching to the “english” mode on the pinyin input method (the shortcut seems to be shift in Ubuntu — FWIW this breaks Firefox in a **different** way), but rather, changing input method entirely (super-space on Ubuntu). We're talking about using the keyboard shortcut, not clicking on anything.

![screenshot from 2015-11-02 12 10 49](https://cloud.githubusercontent.com/assets/1211455/10880394/383f15f0-815b-11e5-9cc4-7c7e19b43638.png)

After switching the IM, completion doesn't resume; you can type characters and they won't bring up any suggestions.

Switching back to pinyin and either committing or cancelling a character restores normal completion.

---

But actually I believe the problem is in Firefox, since trying exactly the same reproduction procedure on a vanilla GTK app (e.g. font picker in The Gimp) doesn't produce the same behaviour (that is, it works just fine).

**Comment by salty-horse** [comment]
This seems to be a [bug in Firefox](https://bugzilla.mozilla.org/show_bug.cgi?id=1219438), so I'll continue there.

Thanks for the help!

**Comment by fujiwarat** [comment]
> FWIW this breaks Firefox in a different way

I don't think so.

> We're not talking about switching to the “english” mode on the pinyin
> After switching the IM, completion doesn't resume

Because you use Super+space to switch to English.
Shift on Pinyin works fine.
