### ISSUE TITLE
`ibus restart` somehow retains old XCompose

### ISSUE THREAD

**Issue by Hi-Angel** [ibus/ibus#1877]
Steps to reproduce:

1. Make sure that ibus is running and configured to input XCompose combinations
2. Edit XCompose file to add or remove a combination
3. Run `ibus restart`
4. Try to type the changed combination, and see that the change didn't happen.

**Comment by fujiwarat** [comment]
I cannot reproduce your problem. The latest version checks the file stamps.

**Comment by Hi-Angel** [comment]
> The latest version checks the file stamps.

Hmm, I seem to have the latest version *(ibus didn't have `--version` option)*:

	$ pacman -Qi ibus | grep ersion
	Version         : 1.5.14-1

In proccess list:

	$ ps -A | grep ibus            
	  591 ?        00:00:37 ibus-daemon
	  602 ?        00:00:00 ibus-dconf
	  638 ?        00:00:13 ibus-engine-sim

@fujiwarat do you have $\*_IM_MODULE and/or $XMODIFIERS set? I didn't set them because gnome-on-wayland doesn't, and still ibus allowed table-input IMs, which makes me think that the variables unneeded anymore.

**Comment by fujiwarat** [comment]
> Hmm, I seem to have the latest version (ibus didn't have --version option):

Did you really run 'ibus --version'? It should show the usage.

> $ pacman -Qi ibus | grep ersion

But this is also fine.

> gnome-on-wayland doesn't, 

OK, you run GNOME Wayland. It's different behavior against non-GNOME desktop.

> $ ps -A | grep ibus

The output does not show any input method engines except for ibus-engine-simple.
From this result, I expect you don't configure any input method sources but XKB sources only on gnome-control-center.
If users do not configure any input method sources, gnome-shell uses gtk-im-context-simple instead of ibus.

If you use compose feature with gtk-im-context-simple, you need to restart gtk client but not ibus:
https://git.gnome.org/browse/gtk+/commit/?id=a41f02f9b1843e0f0085f801430e55f413a9bf9c

**Comment by Hi-Angel** [comment]
> Did you really run 'ibus --version'? It should show the usage.

Right. You probably allude to `version` from the usage, sorry, I just read a few commands to notice that they IM-related, then on quick sight saw nothing starting with `-`, so I overlooked.

> OK, you run GNOME Wayland. It's different behavior against non-GNOME desktop.

Well, I'm testing with both gnome-on-wayland *(I'm going to migrate there once a wayland-specific crash with shell-shape get fixed)*, and i3 *(as my everyday environment)*.

> From this result, I expect you don't configure any input method sources but XKB sources only on gnome-control-center.
> If users do not configure any input method sources, gnome-shell uses gtk-im-context-simple instead of ibus.

Sorry if I do something wrong, but the Internet is surprisingly scarce on the internals of text input. Really, I'm trying to understand how does is work for *more than half-year*, and it's still pretty vague. You can't just google up `linux input method internals`, finding anything at all requires injenious in queries.

So, I just tested again with gnome-on-wayland, and noticed the next unusual behavior: by default `ibus restart` works indeed like you say. However, upon running `setxkbmap -layout us,ru -option grp:rctrl_rshift_toggle,grp_led:scroll,lv3:ralt_switch,compose:rwin` *(which I have to, because `gnome-control-center keyboard → Typing → Switch to next input source` is broken, it ignores any combination of <kbd>Shift</kbd> and <kbd>Control</kbd>)*, `ibus restart` stops working. But [you mentioned yourself](https://github.com/ibus/ibus/issues/1876#issuecomment-253400839) that ibus runs setxkbmap internally, so I've no ideas what's wrong.

**Comment by fujiwarat** [comment]
> linux input method internals

Yeah, the keywords are too vague to resolve your problems.

> However, upon running setxkbmap -layout ...

As I explained previously, you don't have to run '-layout' because both gnome-shell and ibus runs 'ru,us' instead of 'ru'.
You can add "English (US)" and "Russian" on 'gnome-control-center region'.

You can set options for 'setxkbmap -option' as I also explained:
For that option for GNOME, run 'gnome-control-center keyboard' -> 'Typing' -> 'Compose Key',
and run gnome-tweak-tool -> 'Typing'.

> it ignores any combination of Shift and Control.

You can set "Modifiers-only switch to next source" on 'gnome-control-center region'.

> ibus runs setxkbmap internally,

As I explained, if you don't configure any input method sources but XKB input sources only, gnome-shell switches input sources instead of ibus and gnome-shell calls calls XkbLockGroup() internally as I also explained.

Summarize: you don't have to run setxkbmap directly but gnome provides the options which you desired.

**Comment by Hi-Angel** [comment]
> Yeah, the keywords are too vague to resolve your problems.

Err… was it sarcasm? As I explained, the keywords supposed to find anything about IM implementation: what protocol is used between a IM and a client, what's implemented in client for that to work, and what's implemented in the IM. It have little to do with the current problems, except that if I knew how does it work, I'd figured how to fix it on my own.

> As I explained previously, you don't have to run '-layout' because both gnome-shell and ibus runs 'ru,us' instead of 'ru'.
> You can add "English (US)" and "Russian" on 'gnome-control-center region'.
> 
> You can set options for 'setxkbmap -option' as I also explained:
> For that option for GNOME, run 'gnome-control-center keyboard' -> 'Typing' -> 'Compose Key',
> and run gnome-tweak-tool -> 'Typing'.

As I explained previously:

> which I have to, because `gnome-control-center keyboard → Typing → Switch to next input source` is broken, it ignores any combination of <kbd>Shift</kbd> and <kbd>Control</kbd>

Ok.

> > it ignores any combination of Shift and Control.
> 
> You can set "Modifiers-only switch to next source" on 'gnome-control-center region'.

There's no such a button. There's a button `Login Screen` to set a language for login screen, and a button `Options` opening a window with 2 checkboxes for whether windows should use different sources and 4 lines of info. The only button I couldn't check is an image of keyboard, grayed out until a source is chosen. It doesn't do anything, but most likely it ought to show a keyboard layout for the source.

> As I explained, if you don't configure any input method sources but XKB input sources only, gnome-shell switches input sources instead of ibus and gnome-shell calls calls XkbLockGroup() internally as I also explained.

Was your explanation the text that I quoted in the prev. comment? Oh, so nice that you cared to read my answer. Let me paraphrase the reply: you're one of those exceptionally rare peoples who knows how does IMs works on Linux. You could be proud of yourself, if it weren't rather sad.

Your sentence is just confusing: did you mean by "input method sources" vs "XKB input sources" the difference of configuration through the Gnome GUI and setxkbmap? If so, why does that matter if ibus calls setxkbmap internally anyway?

"gnome-shell switches input sources instead of ibus" → but isn't ibus the supplier of input sources?

"gnome-shell calls calls XkbLockGroup() internally" → as I understood from the function description, it probably chooses an input source? If I get guessed right what's the group. Still, I don't understand what it gives me, I thought you mentioned it just for the record.

**Comment by fujiwarat** [comment]
> Err… was it sarcasm?

No, it's not. I mean you don't understand what is your problem by yourself and the keywords are not correct at all.
> the keywords supposed to find anything about IM implementation:

No, you can't find it with the above keywords. At least, "ibus", "implementation" because the implementation is different between input method frameworks. and ibus is one of the input method frameworks so "linux" and "input method" are too vague.

> what protocol is used between a IM and a clien

No, you can't find it with your keywords... At least, "ibus", "protocol", "server", "client".

But anyway you don't have to search those. Your problem is not relative with those.

> You can set "Modifiers-only switch to next source" on 'gnome-control-center region'.

Typo:
You can set "Modifiers-only switch to next source" on 'gnome-control-center keyboard'.

> Was your explanation the text that I quoted in the prev. comment? 

I mean you quoted a part of my explanation but it's not correct quotation.
As I explained, it depends on the input sources configuration which ibus engine's one or gtk-im-context's one is used and your case does not run 'setxkbmap' so the quotation is not correct.

> Your sentence is just confusing: did you mean by "input method sources" vs "XKB input sources" 

No, it's not exactly.
I explained gnome-shell has the different behavior by input sources.

> "gnome-shell switches input sources instead of ibus" → but isn't ibus the supplier of input sources?

No, ibus is not. gnome-shell provides the input sources.

> "gnome-shell calls calls XkbLockGroup() internally" → as I understood from the function description, it probably chooses an input source? I

It indicates two meanings.
One is that your case is to run XkbLockGroup() instead of ibus implementation so setxkbmap is not called in your case.
Another is that XkbLockGroup() also runs "ru,us" instead of "us" because it switches layout in the group so the behavior satisfies your request likes setxkbmap and then after you configure gnome correctly you don't have to/should not, run setxkbmap by yourself.

It seems my typo confused you. Please try 'gnome-control-center region'.

**Comment by fujiwarat** [comment]
> It seems my typo confused you. Please try 'gnome-control-center region'.
No,  'gnome-control-center keyboard' :(

**Comment by Hi-Angel** [comment]
> No, you can't find it with your keywords... At least, "ibus", "protocol", "server", "client".

Thank you. Anyway, i.e. `ibus protocol linux` and `ibus implementation linux` *(`linux` because otherwise too many irrelevant results)* still doesn't give anything about implementation, except for [this answer](http://unix.stackexchange.com/a/262220/59928) with a linked old LWN article about Gnome choosing the default IM engine. I've already read both.

> You can set "Modifiers-only switch to next source" on 'gnome-control-center keyboard'.

Cool, thank you! That's even more than I initially expected from the title, I can choose <kbd>Right Control</kbd>+<kbd>Right Shift</kbd> right there!

> As I explained, it depends on the input sources configuration which ibus engine's one or gtk-im-context's one is used and your case does not run 'setxkbmap' so the quotation is not correct.

What's this configuration? The \*_IM_MODULE variables?

How does ibus behaves on non-gnome desktop, i.e. i3? As I understand the GUI to be used for non-gnome is `ibus-setup`. But I didn't see there a Compose key, so do I have to use `setxkbmap` anyway?

**Comment by fujiwarat** [comment]
> still doesn't give anything about implementation, except for this answer 

The searching words will be too vague until you read the source codes and understand IBus and GTK3 APIs.

> What's this configuration? The *_IM_MODULE variables?

Again:
As I explained, if you don't configure any input method sources but XKB input sources only, gnome-shell switches input sources instead of ibus and gnome-shell calls calls XkbLockGroup() internally as I also explained.

Anyway, I mean either setxkbmap by ibus or XkbLockGroup()  by gnome-shell works fine  without calling setxkbmap directly by yourself, i.e. either GNOME or non-GNOME works fine.

> As I understand the GUI to be used for non-gnome is ibus-setup.

Yes.

> But I didn't see there a Compose key, so do I have to use setxkbmap anyway?

No!

GNOME in case you configure XKB input sources only:
1. Run ``gnome-control-center keyboard`` to configure shortcut.
2. Run ``gnome-control-center region`` to configure more than two XKB input sources likes "US" and "RU".
3. Run ``gnome-tweak-tool`` to set XKB options.
4. Configure $HOME/.XCompose or $HOME/.config/gtk-3.0/Compose for compose keys.

Non-GNOME:
1. Run ``ibus-setup`` to configure shortcuts generally but run ``gsettings`` to configure ``Control-Shift`` instead of ``ibus-setup``.
2. Run ``ibus-setup`` to configure input sources likes "US" and "RU".
3. Google to save XKB options by each desktop.
4. Configure $HOME/.XCompose or  $HOME/.config/gtk-3.0/Compose or $HOME/.config/ibus/Compose for compose keys.

And then you don't have to/should not run setxkbmap directly in your case.

If you configure input method sources on GNOME, mostly same with GNOME in case of XKB input sources but 4 is different:
4. Configure $HOME/.XCompose or  $HOME/.config/gtk-3.0/Compose or $HOME/.config/ibus/Compose for compose keys.
because gnome-shell uses ibus engines instead of gtk-im-context. Both IBus and GTK supports the back compatibility of $HOME/.XCompose in X11.

**Comment by Hi-Angel** [comment]
> Again:
> As I explained, if you don't configure any input method sources but XKB input sources only, gnome-shell switches input sources instead of ibus and gnome-shell calls calls XkbLockGroup() internally as I also explained.
> 
> Anyway, I mean either setxkbmap by ibus or XkbLockGroup() by gnome-shell works fine without calling setxkbmap directly by yourself, i.e. either GNOME or non-GNOME works fine.

Thank you, but just to recap: I don't have to set \*_IM_MODULE variables, neither for gnome, nor for non-gnome, right? In part I'm wondering because `ibus-setup` for manual launch in absence of `ibus-daemon` asks with a popup to set them if something wrong.

> Non-GNOME:
> [snip]
> 3. Google to save XKB options by each desktop.

Thank you, I see. I don't have a DE, just an X11 WM, so I've set the options in the `/etc/X11/xorg.conf.d/00-keyboard.conf`. It works on start, whilst `ibus-daemon` *is not* running, and I see:

	$ setxkbmap -print -verbose 10 | grep layout
	layout:     us,ru

Then I run `ibus-daemon`, and `ru` input source disappears, and I see:

	$ setxkbmap -print -verbose 10 | grep layout
	layout:     us

Note: I have `ru` source set through `ibus-setup`. What do I miss?

**Comment by fujiwarat** [comment]
> I don't have to set *_IM_MODULE variables, neither for gnome

Good point.
You don't have to set GTK_IM_MODULE on GNOME because gnome-shell switches ibus or gtk-im-context-single by input sources configuration instead of GTK_IM_MODULE.
For non-GNOME, it depends on the distro tools however it seems you don't use any tools so you have to export GTK_IM_MODULE=ibus if you use ibus on non-GNOME desktops.
In either GNOME or non-GNOME desktop, you have to export QT*_IM_MODULE.

> $ setxkbmap -print -verbose 10 | grep layout
> layout:     us

Right, If you choose "US" on IBus panel icon, IBus kicks "setxkbmap -layout us".
If you choose "RU" on IBus panel icon, IBus kicks "set xkbmap -layout ru,us".

I don't think "US" layout needs any additional layouts but run "ru,us" for "RU" layout for the control keys.

**Comment by Hi-Angel** [comment]
Thank you, after reading you and some docs, I think I finally start understanding how text input works on GNU/Linux.

In the absence of \*_IM_MODULE variables *ideally* it should be:

1. A client upon getting a keycode *(i.e. key(s) pressed)* calls a libxkbcommon's function to get an according text.
2. libxkbcommon checks its configuration *(i.e. the active input source, options)*, then returns an according text.

In reality that's probably what Qt does. But GTK in absence of `GTK_IM_MODULE` does call not libxkbcommon, but rather

* non-gnome DE: some handmade `GtkImContextSimple` IM, which until recently couldn't even read `~/.XCompose`, and the ability is still raw.
* gnome: something of gnome-shell, which internally does some magic like switching input source and may be calling ibus.

----

When \*_IM_MODULE variables are set:

1. Upon getting a keycode a client calls a function of IM to get a text. Which probably means that both libxkbcommon and IMs are following the same API.
2. An IM does some magic *(like shows up a popup with completions for table-based sources, or calls some of libxkbcommon)*, and returns the text to client.

**Comment by fujiwarat** [comment]
> non-gnome DE: some handmade GtkImContextSimple IM, which until recently couldn't even read ~/.XCompose, and the ability is still raw.

Actually, if GTK3 GtkImContextSimple is set, it also can read ~/.XCompose but not sure if your GTK3 version has this feature.
>> If you use compose feature with gtk-im-context-simple, you need to restart gtk client but not ibus:
>> https://git.gnome.org/browse/gtk+/commit/?id=a41f02f9b1843e0f0085f801430e55f413a9bf9c

We won't touch GTK2 so GTK2 applications (firefox, thunderbird, libreoffice, xchat) cannot read the user compose files until they move to GTK3.

If GTK_IM_MODULE is not set, which IMF is used is different by distro's ``/usr/lib64/gtk-3.0/*/immodules.cache`` but maybe gtk-im-context-simple or xim.

>> Upon getting a keycode a client calls a function of IM to get a text. Which probably means that both libxkbcommon and IMs are following the same API.

We implemented compose key features in both gtk-im-context-simple and ibus from the scratch so the behaviors are same but APIs are not referred and GTK and QT have the owned APIs to work with the keycodes, keysyms.

**Comment by Hi-Angel** [comment]
> Actually, if GTK3 GtkImContextSimple is set, it also can read ~/.XCompose but not sure if your GTK3 version has this feature.

Right, but it's still raw for everyday use. I know for sure because I'm the author [of this bugreport](https://bugzilla.gnome.org/show_bug.cgi?id=768624).

FTR to occasional reader: from my last day experiments, the best support of XCompose so far implemented in xim and fcitx. But fcitx support made in a very interesting way: one have to set \*_IM_MODLE's and XMODIFIERS to `fcitx` and `@im=fcitx`, *but not to run the fcitx daemon*, i.e. to leave XKB just configured via config, like:

	Section "InputClass"
			Identifier "system-keyboard"
			MatchIsKeyboard "on"
			Option "XkbLayout" "us,ru"
			Option "XkbModel" "pc105"
			Option "XkbOptions"    "grp:rctrl_rshift_toggle,grp_led:scroll,lv3:ralt_switch,compose:rwin"
	EndSection

For fcitx daemon is running, something *(don't remember what)* is not right.

**Comment by fujiwarat** [comment]
>>  Actually, if GTK3 GtkImContextSimple is set, it also can read ~/.XCompose but not sure if your GTK3 version has this feature.

>  Right, but it's still raw for everyday use. I know for sure because I'm the author of this bugreport.

No, I think you don't understand my mention.
I mean I implemented the compose features in GTK3 too but I'm not sure if your GTK3 version is the latest.
Your GNOME bugzilla should be closed.

Reading the bugzilla, I got the information of https://github.com/kragen/xcompose/blob/master/dotXCompose .
I tried that file and it works fine in both ibus and gtk3.
E.g.
Multi_key+period+period outputs "…"   U2026  correctly.

**Comment by Hi-Angel** [comment]
> I tried that file and it works fine in both ibus and gtk3.
> E.g.
> Multi_key+period+period outputs "…" U2026 correctly.

Do you mean you just tried some combinations like "…" *(which is vanilla one anyway)*, or that it didn't output the errors for you? Can you e.g. type [this one](https://github.com/kragen/xcompose/blob/a6871a9c142fb64e5bda33cc241afe258dbf9cbe/dotXCompose#L350):

	<Multi_key> <Multi_key> <i> <i> <i> <n> <t>     : "∭"   U222D           # TRIPLE INTEGRAL

[and](https://github.com/kragen/xcompose/blob/a6871a9c142fb64e5bda33cc241afe258dbf9cbe/dotXCompose#L43)

    <Multi_key> <space> <minus> : " — " # EM DASH surrounded by THIN SPACEs.

**Comment by fujiwarat** [comment]
> Multi_key Multi_key i i i n t    : "∭"   U222D 
> Multi_key space minus : " — " # EM DASH

No, the multiple characters are not supported in gtk and ibus at the moment.
See issue #1819

**Comment by Hi-Angel** [comment]
> No, the multiple characters are not supported in gtk and ibus at the moment.

Well this one

	<Multi_key> <Multi_key> <i> <i> <i> <n> <t>     : "∭"   U222D           # TRIPLE INTEGRAL

is a single character, the error it triggers is `The max number of sequences is 7`.

There're also parsing errors, like `No delimiter ':'` for a line consisting of a single comment.

**Comment by fujiwarat** [comment]
> is a single character, the error it triggers is The max number of sequences is 7.

Yes, both gtk and ibus works on less than 7 sequences.
Probably you can change the sequences to ``"<Multi_key> <Multi_key> <3> <i> <n> <t>"`` for examle.

**Comment by fujiwarat** [comment]
Recording for who would like to get debug messages about compose tables.

In case of IBus (GTK_IM_MODULE=ibus):
```
% rm $HOME/.cache/ibus/compose/*
% vi $HOME/.config/ibus/Compose
% ibus exit
% env IBUS_COMPOSE_TABLE_PRINT=1 ibus-daemon --xim --verbose &
% gedit
```

In case of GtkIMContextSimple (GTK_IM_MODULE=gtk-im-context-simple) (in case of GNOME)
```
% rm $HOME/.cache/gtk-3.0/compose/*
% vi $HOME/.config/gtk-3.0/Compose
% env GTK_COMPOSE_TABLE_PRINT=1 gedit
```
