### ISSUE TITLE
Korean input

### ISSUE THREAD

**Issue by billyjin** [ibus/ibus#1881]
Dear 
I've used IBUS several years as default ubuntu IME.
But it's not still solved for Korean input.

In Korean, Spacebar means the end of term.

If I'm trying to input "나는 사람이다."
Your IME input " 나 는사람이다."
It's completely wrong to understand. 

So my solution was input "Ctrl " after  every term. 
for example , 
"나" + "Ctrl" + "는" + "Ctrl" + "Space bar"  + "Ctrl" +"사" + "Ctrl" +"람" + "Ctrl" +"이" + "Ctrl" +"다" 
it's working  well.

How about to modify ibus-hangul as my idea.

**Comment by fujiwarat** [comment]
Probably I think your workaround will cause a significant regression bugs since it binds Ctrl + Space keys and I don't agree with it.

I think the actual workaround is to use GTK or Qt applications.
Your problem affects X11 applications only.
If not, your configuration is not correct.
So I think the actual problem exists in the limited situation.

You can comment here if you have another questions.
