### ISSUE TITLE
No instructions on how to copy settings from machine A to machine B

### ISSUE THREAD

**Issue by jidanni** [ibus/ibus#1902]
Many users use more than one computer.
They wish to have the same settings on their other computer.
Apparently one must copy the file
```.cache/ibus/bus/registry```
from their first computer to their second computer to make this happen.
Please document that in README.

**Comment by fujiwarat** [comment]
The cache file is generated from /usr/share/ibus/component/*.xml and the cache depends on which ibus engines are installed so I don't recommend to copy that file.
If you wish to create the user file per user, you can run `ibus write-cache`.
But you can create a system file with `ibus write-cache --system`.
We have already provided ibus(1) man page.
But basically it's each engine bug. When an ibus engine is installed, the post install script should run `ibus write-cache` so that ibus-daemon won't have to create the cache file by user.

E.g. ibus-anthy runs it in post install:
http://pkgs.fedoraproject.org/cgit/rpms/ibus-anthy.git/tree/ibus-anthy.spec#n124
