### ISSUE TITLE
Pinyin input method unusable when switching to it from non-English layout

### ISSUE THREAD

**Issue by salty-horse** [ibus/ibus#1912]
Using ibus 1.5.14

If I switch from a non-latin layout, e.g. Russian or Hebrew, to Pinyin, key presses are interpreted as the last-used layout instead of English, and nothing happens.

Is it possible for IBus to allow input method developers to force a particular layout to use?

**Comment by mike-fabian** [comment]
Yes, that is possible and some input methods like Cangjie and Wubi which can only work with
a certain keyboard layout do that.

But pinyin is usable with any keyboard layout which can input ASCII, i.e. pinyin works just fine
with a German or French keyboard layout.  It would not be nice to force a Us keyboard layout for pinyin.

**Comment by fujiwarat** [comment]
You can modify `<layout>` tag in `/usr/share/ibus/component/libpinyin.xml`.
The default behavior follow the previous layout since libpinyin does not work with `en` only but also `en` `drovak` variant.
If you would the GUI customization, you could ask ibus-libpinyin.

**Comment by J-J-Chiarella** [comment]
While I understand the desire of some to have non-QWERTY layouts for pinyin -- i.e., being able to type "zhong 中" on the AZERTY layout using what would be "whong" on the US-Eng keyboard -- the default behavior for every other input method editor for every other platform that I have seen defaults to using underlying US-Eng.

In fact, this standard (US-Eng) is so ubiquitous that other input method editors like hangul use this layout. Within Hangul (Korean script) are three switchable input methods -- Latin script, hangul and Korean version of 漢字 (hanja). Japanese script can do a 1:1 mapping of the Q key to the た hiragana, or it can be used like pinyin -- write a syllable in semi-phonetic Latin and then convert to the string to a single Japanese character. Here, the underlying keyboard is assumed to be US English.

Since fujiwarat closed this bug and suggested contacting ibus-pinyin, I think it may be wise to do so.

For ease of transition to Linux, we need to pay attention to how people use their computers.

It would probably make sense to change ibus-pinyin thus:

1. Have an option in the GUI to use underlying US-Eng for pinyin input.
2. Have the option set to US-ENG by default.
3. Have an option to do one of the following: (a) use whatever the last other input method was that was *also* a Latinate layout, or (b) select a different underlying input method.

I think (b) would be the better option. If someone wants to type pinyin with the "q" and "a" flip-flopped in their geographic positions, so be it -- but it should be "opt-in" and *not* the default.

**Comment by fujiwarat** [comment]
@J-J-Chiarella I meant ibus-libpinyin but not ibus-pinyin.

**Comment by alex-rusakevich** [comment]
Sorry for necroposting, but this problem is still actual in 2024. Run

```sh
sed "s/<layout>default<\/layout>/<layout>cn<\/layout>/g" /usr/share/ibus/component/libpinyin.xml | sudo tee /usr/share/ibus/component/libpinyin.xml
```

And then restart your computer to fix it.

Before running this command I couldn't type anything in Chinese, the result always was like "тшрфщ" instead of 你好 or at least nihao

**Comment by fujiwarat** [comment]
> Before running this command I couldn't type anything in Chinese, the result always was like "тшрфщ" instead of 你好 or at least nihao

As I said, you should set en layout before you set pinyin and it's an engine issue but not ibus core.
ibus-anthy already provides the keyboard customization.
