### ISSUE TITLE
1.5.0以上光标丢失问题

### ISSUE THREAD

**Issue by panosliu** [ibus/ibus#1937]
都是切换输入法光标丢失的问题
现象1:
在gtk, qt.或java 的另存对话框里创建文件夹，切换输入法后光标丢失。
1.5.0以上版本有这个问题，1.4.2没有这个问题。

现象2
firefox 打开一个网页，一个绑定textarea的div标签里切换输入，光标丢失，不能输入，需要鼠标点进入才能输。
1.5.0以上版本有这个问题，1.4.2没有这个问题。
opera, chrome没有这个问题。

不清楚1.4.2到1.5.0是什么改动引起这个问题？

**Comment by fujiwarat** [comment]
I don't see any cursor problems.
Can you attach the screenshots for the case 1 and 2?
Each desktop provides a screenshot tool. 
E.g. `gnome-screenshot -i` for GNOME.

**Comment by panosliu** [comment]
case 1. 
Please see the attached screenshot
![out](https://user-images.githubusercontent.com/1025386/29153319-81bc1efa-7dbf-11e7-921f-2a5e8a6b3269.jpg)

fcitx is ok
![fcitx](https://user-images.githubusercontent.com/1025386/29153338-948cd646-7dbf-11e7-9abe-bf4019cfcc9e.jpg)

**Comment by fujiwarat** [comment]
Seems your example is gedit?
I think GEdit uses GTk3 file-chooser dialog since fedora 24 and I think the problem does not happen because the dialog's input field is enhanced.
I tried leafpad and it uses GTK2 file-chooser and I can reproduce your problem.
Yes, Super-space causes FocusIn -> FocusOut -> FocusIn on the application so if the application's spec resets the cursor position when it receives FocusOut, you could see your problem.
Super-space uses XI2 keybindings and XI2 have this issue. Probably I won't change the XI2 implementation.
So it's good to fix your application.
But if you're saying to switch Chinese and English, I'd recommend to use pinyin's short cut key instead of IBus core.
I think Pinyin provides the Shift key to switch Chinese and English mode.
The Shift key works for you?

**Comment by fujiwarat** [comment]
@panosliu Any replies?
