### ISSUE TITLE
Can not input chinese using ibus in Foxit Reader with QT5

### ISSUE THREAD

**Issue by ray-github-hybrid** [ibus/ibus#1968]
OS: Fedora 26
Architecture: x86_64
IBus version: 1.5.17
Input method name and version: ibus-libpinyin 1.9.0
Python version: 2.7.14
GTK version: 3.24.2
QT5 version: 5.9.2

What steps will reproduce the problem?
1. Installation of foxit reader for linux（https://www.foxitsoftware.com/pdf-reader/）
2. Open foxit reader and any pdf file
3. Can not input Chinese (maybe other languages except English) in search frame or comments

Actually, I can not change English/Chinese by pressing SHIFT in intelligent pinyin. It seems ibus is frozen.
BUT, I can input chinese in QT5-designer, which is installed from official repository.

**Comment by fujiwarat** [comment]
I could reproduce your problem but it has the owned opt/foxitsoftware/foxitreader/platforminputcontexts/libibusplatforminputcontextplugin.so and does not use /usr/lib64/qt5/plugins/platforminputcontexts/libibusplatforminputcontextplugin.so .
I almost give up to debug the closed source codes.
Since Qt5 is based on C++, there is no binary compatibility between the system qt5 and foxitreader one.
Can you report  your problem to https://www.foxitsoftware.com/pdf-reader and ask them to debug opt/foxitsoftware/foxitreader/platforminputcontexts/libibusplatforminputcontextplugin.so ?

**Comment by fujiwarat** [comment]
The workaround is:
```
% env QT_IM_MODULE=xim FoxitReader
```
