### ISSUE TITLE
Setting the DBus address for IBus

### ISSUE THREAD

**Issue by ammgws** [ibus/ibus#1969]
Hi, I tried posting over at `ibus-user` but my posts don't seem to have gone through so please let me ask here.

I want to retrieve the DBus address used by `ibus-daemon` so that I can listen to events such as `GlobalEngineChanged`. I know that the address can be parsed from the file `~$XDG_CONFIG_HOME\ibus\bus\<machineid-hostname-displaynumber>`, but from limited testing I found it to be unreliable as the address would sometimes change during the same user session and my client program would be none the wiser.

**Question: Is there a way to set the address ourselves?**
I found reference to [this env var](https://github.com/ibus/ibus/blob/af66ace771fc16a23e7a5841d2f0bd79789e009d/src/ibusshare.c#L191) `IBUS_ADDRESS`, however I don't understand how it comes into play since in the `ibus-daemon` setup the [address is provided by DBus](https://github.com/ibus/ibus/blob/9937a0e4501ccf0cfd238ce7c97733c3099db3f7/bus/server.c#L168), and `IBUS_ADDRESS` does not appear to be used anywhere else in the code.

**Comment by fujiwarat** [comment]
> but from limited testing I found it to be unreliable as the address would sometimes change during the same user session

I think the address should be changed by launching ibus-daemon.

> I found reference to this env var IBUS_ADDRESS

The variable is for the ibus clients in case they cannot access the disc path. ibus-daemon saves the address with [ibus_write_address()](https://github.com/ibus/ibus/blob/master/bus/server.c#L173).

I think you should connect IBusBus::disconnected signal instead of trying the unchanged address.

**Comment by ammgws** [comment]
> The variable is for the ibus clients in case they cannot access the disc path. 

When/where in the code is this variable set? 
[ibus_get_address()](https://github.com/ibus/ibus/blob/af66ace771fc16a23e7a5841d2f0bd79789e009d/src/ibusshare.c#L178) retrieves the address from that variable or from the disk path, but [ibus_write_address()](https://github.com/ibus/ibus/blob/af66ace771fc16a23e7a5841d2f0bd79789e009d/src/ibusshare.c#L238) only writes to the disk path.


> I think you should connect IBusBus::disconnected signal instead of trying the unchanged address.

Thanks, I will look into this as well.

**Comment by fujiwarat** [comment]
> When/where in the code is this variable set?

So when the ibus clients cannot access the disc path, e.g. NIS mount failure in $XDG_CONFIG_HOME/ibus/bus. You don't have to think $IBUS_ADDRESS basically.
ibus-daemon writes the address with ibus_write_address() and ibus clients get the address with ibus_get_address().

**Comment by ohk2kt3t4** [comment]
Sorry to dig up this old thread, but I have been investigating issues on my system most likely due to #2116 and would like to double check the following regarding the ibus address.

Is this correct:

If run `ibus-daemon --address unix:path=/run/user/1000/ibus.socket`, then ibus-daemon should use the specified address instead of the [default](https://github.com/ibus/ibus/blob/91a256163427f04eb7763196b4ffe553911d2e01/bus/global.c#L27) `unix:tmpdir=/tmp/ibus`. 

In this case, the contents of `$XDG_CONFIG_HOME/ibus/bus` should be something like:
```
# This file is created by ibus-daemon, please do not modify it
IBUS_ADDRESS=unix:abstract=/run/user/1000/ibus.socket,guid=7542d73dce451c2461a042e24bc131f4
IBUS_DAEMON_PID=11140
```

And thus I should be able to avoid the current issues regarding the default socket file location.


---

My understanding of the code:
1) The address given by CLI argument is stored in `g_address` [[relevant code](https://github.com/ibus/ibus/blob/32645ca8070db1f8b6360b07b229829ed6033437/bus/main.c#L77)]
2) `g_address` is supplied to `g_dbus_server_new_sync()` which [creates ](https://github.com/ibus/ibus/blob/7a38e4d18ea4023f01948c6ce2fe303dbe4b3bd9/bus/server.c#L152-L157)a DBus server that listens on the address given in `g_address`
3) ibus-daemon calls `g_dbus_server_get_client_address()` to get the DBus address string for the server created in step 2. 
 If `g_address` was a socket file path then the DBus address will be same as `g_address`, otherwise `GDBusServer` will create a randomly named socket file in the directory specified by `g_address` i.e.  `unix:abstract=/user/specified/path/dbus-randomstr` 
3) ibus-daemon writes the address path to `$XDG_CONFIG_HOME/ibus/bus` [[relevant code](https://github.com/ibus/ibus/blob/7a38e4d18ea4023f01948c6ce2fe303dbe4b3bd9/bus/server.c#L169-L174)]

**Comment by fujiwarat** [comment]
> In this case, the contents of `$XDG_CONFIG_HOME/ibus/bus` should be something like:
> IBUS_ADDRESS=unix:abstract=/run/user/1000/ibus.socket,guid=7542d73dce451c2461a042e24bc131f4

If you specify unix:path, the IBUS_ADDRESS also specifies unix:path but not unix:abstract.

> My understanding of the code:

I think you're right.

> Reason I am checking is because I am starting ibus as a systemd user service, and even though I am specifying the address socket path `ibus-daemon` is still using the default `/tmp/ibus/` path. So either I am misunderstanding the `--address` parameter, or something is going wrong.

I guess it means the ibus-daemon is not called by systemd but another program?

**Comment by ohk2kt3t4** [comment]
> I guess it means the ibus-daemon is not called by systemd but another program?

It turns out that I was indeed starting it via my compositor and not systemd. When the new update broke ibus I started troubleshooting using an unused systemd user file I had lying around, forgetting that I wasn't actually using it. Sorry for the noise.

**Comment by fujiwarat** [comment]
BTW, I noticed unix:path is wrong. If you kill -9 ibus-daemon, you no longer restart ibus-daemon because the old socket path is persistent.
