### ISSUE TITLE
ibus 1.5.15 breaks CTRL+SHIFT+U unicode?

### ISSUE THREAD

**Issue by yubo56** [ibus/ibus#1981]
Please fill in the following items if you don't know the root cause.

Which distribusion and version?: Archlinux 

Which desktop environment and version?: None (I use dwm window manager, no DE)

Which session type?: X11

Which application and version?: All (first observed in chromium)

IBus verion?: 1.5.15

Issue description: CTRL+SHIFT+U no longer outputs unicode

Steps to reproduce:
1. Install ibus version 1.5.14 (I used 1.5.14-2 on the archlinux repository)
2. Type CTRL+SHIFT+U, release, then press 0069 (for instance). `i` should be typed
3. Install ibus version 1.5.15
4. Type CTRL+SHIFT+U, release, then press 0069 (for instance). `0069` should be typed
5. Kill ibus
6. Type CTRL+SHIFT+U, release, then press 0069 (for instance). `i` should be typed

Can you reproduce your problem when you restart ibus-daemon? (yes / no): yes

Do you see any errors when you run ibus-daemon with the verbose option?: no

Can you reproduce your problem with a new user account instead of the current your account? (yes / no): yes

-----------------------------------------------------------------------------------------------------------------------------

https://github.com/ibus/ibus/issues/1889 seems like this issue discusses that 1.5.15 forwards CTRL+SHIFT+U directly to application, so it seems to be bypassing gtk which is responsible for interpreting unicode input. Is it possible to preserve this behavior?

**Comment by yubo56** [comment]
I'm not sure whether there are any other open/closed issues that discuss this, feel free to close or point to other discussion.

**Comment by fujiwarat** [comment]
Since IBus 1.5.15, the feature of Ctrl-Shift-u was consolidated to Ctrl-Shift-e and also the feature is moved from IBus client to IBus panel. The issue ID is right. The previous implementation had the hard-coded short cut keys in IBus client and now it's moved to IBus panel so that the shortcut key can be customized with ibus-setup.
You could output that Unicode character with Ctrl-Shift-e, type 69, and Enter key if `ibus-ui-gtk3` is running.

**Comment by yubo56** [comment]
Ah I didn't realize that emoji search supports unicode codes, thanks!

**Comment by Slider-Whistle** [comment]
Using a window popup is not an acceptable replacement for the previous functionality

**Comment by MarkJeronimus** [comment]
It seems this has regressed in iBus 1.5.17.

Ctrl+Shift+u which previously did nothing (presuably I've always used 1.5.15) now works as before, giving an underlined 'u'.

Side note, Ctrl+Shift+e does nothing, even though it's configured correctly in ibus-setup.

**Comment by Slider-Whistle** [comment]
Oh really? That'd be a relief.
My earlier post probably could've been a little more constructive, so what I meant was that:
- Directly entering the codepoint might be useful when you know that, and not the descriptor/name of the symbol (for example, if a web page shows unicode symbols and their codepoints, just typing them would be more convenient than pasting them into a search engine to figure out the name of that one pseudographic tile and make a triforce, or something)
- Not all characters have descriptions already, especially not control characters which you figure would be one of the first priorities
- Window popups are just plain annoying, especially in unconventional window managers

**Comment by fujiwarat** [comment]
@Slider-Whistle you should try 1.5.19 or later.

**Comment by MarkJeronimus** [comment]
I think you misunderstood me. Grabbing Ctrl+Shift+u without an option to disable it is a bothrer, because it's the shortcut for 'convert to upper-case' or 'toggle upper-case' in many IDEs and editors I use, and I use it often enough that it's burnt into my muscle memory.

**Comment by Slider-Whistle** [comment]
@fujiwarat Thanks, and sorry if my earlier comment came across as being a little rude.

**Comment by MarkJeronimus** [comment]
No worries. I know the pain of seeing a bug report for an older version. I did not know that 1.5.19 was out when I posted the regression report because I'm at the 'newest' version according to bionic. I'm not even sure it's regression though, because I can't even go back to 1.5.15 to test.

**Comment by fujiwarat** [comment]
@MarkJeronimus The latest ibus-setup has the customization of the shortcut keys.

**Comment by Slider-Whistle** [comment]
> Using a window popup is not an acceptable replacement for the previous functionality

Sorry for making a comment years later out of nowhere. I just wanted to apologise for this saying this again. It was completely self-entitled of me.
I'm sure there's fringe purposes for it, like maybe weird people who just want to see what's at a certain codepoint, or somehow do some hex editing without a hex editor, but it turns out that I completely overestimated how useful Control+Shift+u really is. Most of those codepoints pick out their appropiate entry in the emoji picker anyway, at least if my configuration's standard.
It did make me feel a little sour to see that feature disappear in a way that appeared to be unannounced (especially before I took the time to understand the new feature), but it didn't warrant my earlier rudeness.
