### ISSUE TITLE
(Question) GTK+ supports to output one char only

### ISSUE THREAD

**Issue by Nekotekina** [ibus/ibus#1982]
https://github.com/ibus/ibus/blob/master/src/ibuscomposetable.c#L112
Why? What is the rationale behind it?

**Comment by fujiwarat** [comment]
This code was integrated from [GTK](https://gitlab.gnome.org/GNOME/gtk/blob/master/gtk/gtkcomposetable.c#L114)

I noticed the current code can output one char only and added the warning in both ibus and gtk.
Probably I guess the reason is that the first implementation didn't expect more than one char.
The data entity is https://github.com/ibus/ibus/blob/master/src/gtkimcontextsimpleseqs.h and it's a difficult for me to support the multiple char and keep the current algorithm.

If you could provide the patch to GTK, it would be great.
You can use IBus emojier instead, which can output multiple characters with an annotation.
