### ISSUE TITLE
ibus doesn't appear in the tray when configured with gconf

### ISSUE THREAD

**Issue by yurivict** [ibus/ibus#1993]
OS: FreeBSD 11.1
Version: 1.5.17

**Comment by fujiwarat** [comment]
Your description is too short. Please use the bug template and how did you install ibus?

**Comment by fujiwarat** [comment]
Did you install ibus from ports?
How do you know IBus is configured with GConf?

**Comment by yurivict** [comment]
Port's option is GCONF=yes

**Comment by fujiwarat** [comment]
I don't know about Ports. Do you mean Ports build the package in your local directory instead of installing the pre-built package.
If so, you need to describe how did you build ibus with ports.

**Comment by yurivict** [comment]
> I don't know about Ports. Do you mean Ports build the package in your local directory instead of installing the pre-built package.

Port can be directly installed, or can create a package which can be installed. The two ways are identical. 'portupgrade -f ibus' force-upgrades this port from ports.

**Comment by fujiwarat** [comment]
I mean Gconf should be specified in the build time. So if GCONF=yes is applied in the installation time, it does not effect.

**Comment by fujiwarat** [comment]
> Port can be directly installed

If Port can install the pre-build ibus, it's good for you to install it if you don't understand how to build ibus.

**Comment by yurivict** [comment]
> If Port can install the pre-build ibus, it's good for you to install it if you don't understand how to build ibus.

Yes, it is applied at build time. It's an option, not an environment variable.
When MEMCONFIG option is selected, it also doesn't show in the tray.
So only DCONF works.

**Comment by yurivict** [comment]
Please fix this.

**Comment by fujiwarat** [comment]
And then the option would not be correct because once the ibus package is built, you cannot select any options for the built binaries.
I think it's good to disable that option in Ports.
I guess someone maintain the IBus in ports? I think it's good to ask them to update the ports configuration.
Myself does not have an opportunity to build ibus with ports.

Thanks.

**Comment by yurivict** [comment]
> And then the option would not be correct because once the ibus package is built, you cannot select any options for the built binaries.

Nobody selects options in the runtime. The way it works is that one of them is default, and people who want other options choose them locally and rebuild with these options.

But this isn't a problem here. The problem is that memconf and gconf don't work, it doesn't appear in tray.

**Comment by fujiwarat** [comment]
> Nobody selects options in the runtime. 

Ah, ok. I mistook runtime with build time. Sorry.

> The problem is that memconf and gconf don't work, it doesn't appear in tray.

You need to describe how to build memconf and gconf.

**Comment by yurivict** [comment]
In FreeBSD:
1. cd /usr/ports/textproc/ibus
2. make config
... select GCONF
3. make install clean

MEMCONF isn't supported by the port yet, I will add it later.

**Comment by yurivict** [comment]
> Reading #1994, did you disable DCONF?

Yes, only one option is enabled.

**Comment by fujiwarat** [comment]
Try to answer the template at first.

Can you reproduce your problem when you restart ibus-daemon? (yes / no): 
(Run `ibus exit` and `ibus-daemon --xim &`)

Do you see any errors when you run ibus-daemon with the verbose option?:
(Run `ibus-daemon --xim --verbose &` and look at the output when you encounter your problem.)


Can you reproduce your problem with a new user account instead of the current your account? (yes / no):

**Comment by fujiwarat** [comment]
Also try to fill the template.

Which desktop environment and version?: 
(E.g. GNOME 3.24. Check $XDG_CURRENT_DESKTOP and your ISO image.)

Which session type?: 
(X11 or Wayland. Check $XDG_SESSION_TYPE)

Which application and version?: 
(E.g. gedit 3.24, leafpad, kate, xterm)

**Comment by yurivict** [comment]
Session and desktop are in my original post.
Application is not applicable.

**Comment by yurivict** [comment]
Please reopen this. This is a real problem.

**Comment by fujiwarat** [comment]
Again
Try to answer the template at first.

Can you reproduce your problem when you restart ibus-daemon? (yes / no):
(Run ibus exit and ibus-daemon --xim &)

Do you see any errors when you run ibus-daemon with the verbose option?:
(Run ibus-daemon --xim --verbose & and look at the output when you encounter your problem.)

Can you reproduce your problem with a new user account instead of the current your account? (yes / no):

**Comment by yurivict** [comment]
> Can you reproduce your problem when you restart ibus-daemon? (yes / no):
> (Run ibus exit and ibus-daemon --xim &)

It can't be restarted because it doesn't start at all with GCONF=yes.

> Do you see any errors when you run ibus-daemon with the verbose option?:
> (Run ibus-daemon --xim --verbose & and look at the output when you encounter your problem.)

With GCONF=yes, it prints these and doesn't show in the tray:
```
(ibus-ui-gtk3:60571): IBUS-WARNING **: panel.vala:308: If you launch KDE5 on xterm, export XDG_CURRENT_DESKTOP=KDE before launch KDE5.
(ibus-ui-gtk3:60571): GLib-GIO-ERROR **: Settings schema 'org.freedesktop.ibus.general' is not installed
```

With DCONF=yes, it prints these but shows in the tray:
```
(ibus-ui-gtk3:83787): IBUS-WARNING **: panel.vala:308: If you launch KDE5 on xterm, export XDG_CURRENT_DESKTOP=KDE before launch KDE5.
(ibus-ui-gtk3:83787): IBUS-WARNING **: ibus_bus_call_sync: org.freedesktop.DBus.Properties.Get: GDBus.Error:org.freedesktop.DBus.Error.Failed: No global engine.
(ibus-ui-gtk3:83787): Gdk-CRITICAL **: gdk_window_thaw_toplevel_updates: assertion 'window->update_and_descendants_freeze_count > 0' failed
(ibus-ui-gtk3:83787): IBUS-CRITICAL **: ibus_serializable_deserialize: assertion 'g_type_is_a (type, IBUS_TYPE_SERIALIZABLE)' failed
(ibus-ui-gtk3:83787): IBUS-CRITICAL **: ibus_emojier_update_emoji_to_data_dict: assertion 'data != NULL' failed
(ibus-ui-gtk3:83787): IBUS-CRITICAL **: ibus_emojier_update_annotation_to_emojis_dict: assertion 'data != NULL' failed
(ibus-ui-gtk3:83787): IBUS-CRITICAL **: ibus_emojier_update_category_to_emojis_dict: assertion 'data != NULL' failed
```

> Can you reproduce your problem with a new user account instead of the current your account? (yes / no):

Yes, I reproduced it in a freshly installed VM with FreeBSD 11.1.

**Comment by fujiwarat** [comment]
> It can't be restarted because it doesn't start at all with GCONF=yes.

I think you mean ibus-ui-gtk3 cannot be running but ibus-dameon is still running?

> (ibus-ui-gtk3:60571): GLib-GIO-ERROR **: Settings schema 'org.freedesktop.ibus.general' is not installed

Your installation is not correct.
See "Install gsettings schemas file" in https://github.com/ibus/ibus/wiki/Install

> (ibus-ui-gtk3:83787): IBUS-CRITICAL **: ibus_emojier_update_emoji_to_data_dict: assertion 'data != NULL' failed

Your installation is not correct.
You should build ibus with emoji data. You can see the output after you run `configure`.

That's why I close your issue immediately unless you submit your issue with the bug template.
