### ISSUE TITLE
don't break C-S-u

### ISSUE THREAD

**Issue by matthiasclasen** [ibus/ibus#1998]
I noticed that ibus now breaks expected user experience by not responding to C-S-u anymore.
This is really not acceptable in my view. An environment variable to enable a UI feature like this
is really really the wrong approach. Please reconsider this.

**Comment by fujiwarat** [comment]
I think some users expect C-S-u enables the Unicode code points and some ones (especially in Java users) do the shortcut key enables each client application binding [[1](https://github.com/ibus/ibus/issues/1889)]. C-S-u in the ibus IM module had followed GtkIMContextSimple and I think the problem is the keybinding would not be customizable and it would be available in GTK applications only.

Now the ibus keybinding is moved to IBusEngine instead of IM module and IBusEngine uses GSettings to be able to customize the keybinding.
I also think we don't have to provide both C-S-u and C-S-e because the Unicode code point can be consolidated to C-S-e.

If you'd suggest it's really not acceptable for the back compatibility, I'd propose the key "hotkey" in GSettings schema "org.freedesktop.ibus.panel.emoji" have the value of both C-S-e and C-S-u.

Currently I'm also thinking if the input focus can be moved from the dialog to input contexts in client applications.

**Comment by priyadi** [comment]
I'm using a keyboard macro to input unicode characters using C-S-U. this worked in 1.5.12. Now my distro has upgraded ibus, this no longer works.

I tried adapting using C-S-E. but it pops up a GUI and makes it unreliable. after adding delay here and there, most of the time it works, but sometimes it doesn't. The old method worked reliably without any delay. Would you consider restoring the old GUI-less method?

**Comment by mcatanzaro** [comment]
If you're concerned that C-S-u conflicts with application shortcuts, then surely adding C-S-e was not a good idea...?

Super+u and Super+e seems like the generally-accepted way to avoid clashing with application shortcuts.

**Comment by matthiasclasen** [comment]
Super+u is going to be problematic for this, I'm afraid. I am pretty sure that the special handling of Super in gnome-shell is going to interfere with the kind of modal editing that C-S-u currently offers, and that users have come to expect.

Please, just give us C-S-u back.

**Comment by fujiwarat** [comment]
Now I moved Ctrl-Shift-e and Ctrl-Shift-u to ibus-panel-extension, which can be customizable with ibus-setup
https://github.com/ibus/ibus/commit/5ee3f48049ecf128391da6448ae7e74786bd171b
