### ISSUE TITLE
The icon in the task bar is not visible on a dark panel

### ISSUE THREAD

**Issue by Azarilh** [ibus/ibus#2017]
Which distribution and version?: Kubuntu 18.04
Which desktop environment and version?: KDE Plasma 5.12.5
Which session type?: X11
IBus version?: 1.5.17

Issue description:
I really don't understand why you still didn't put the possibility to change the color of the icon in the task bar. Its blue color is not easly visible on a dark panel, it's annoying.

**Comment by fujiwarat** [comment]
I think you mean the system tray but not task bar.
You can change it with gsettings:
```
% gsettings get org.freedesktop.ibus.panel xkb-icon-rgba
'#415099'
```

**Comment by Azarilh** [comment]
Yes, system tray... Thank you. Ibus is not user-friendly.

**Comment by fujiwarat** [comment]
Because I think the default color works fine with the default theme in almost desktops and the customizing foreground color would not be a main feature.
And the color setting does not support a simple foreground color only but also color patterns likes tile, shade, transparent. I have no idea about the GUI to cover all the settings.

**Comment by Arkady23** [comment]
How can I change this color and size. Nothing is visible. I have Linux debian 11.5 stable, Cinnamon Desktop.
![image](https://user-images.githubusercontent.com/79393209/194982568-bcf27b8d-2eb5-4376-bfae-7d0517758e45.png)
