### ISSUE TITLE
typing emoji / codepoint names with spaces

### ISSUE THREAD

**Issue by codl** [ibus/ibus#2047]
is there a way to type a space into the emoji/codepoint picker?

for example if I want a zero width non joiner, i press ctrl+shift+e, type "zero" and when I press space, I end up with "0" and I have to search for the right character through the picker widget

typing without spaces, like "zerowidth", doesn't work

**Comment by mike-fabian** [comment]
You can do something like that with ibus-typing-booster (or emoji-picker, which comes with ibus-typing-booster):

http://mike-fabian.github.io/ibus-typing-booster/documentation.html#emoji-input-multiple-keywords

http://mike-fabian.github.io/ibus-typing-booster/documentation.html#emoji-picker

**Comment by fujiwarat** [comment]
In 1.5.18, Shift-space was supported to insert the space but I forgot to migrate it to 1.5.19.
Please back port the fix; https://github.com/ibus/ibus/commit/e6badb494e0a31b7aca3a5078a5dc5b27b83390d
Since Space key is used to convert the annotation to emojis, Shift-space is used to insert the space character. See also the man page of ibus-emoji(5).

Also several useful fixes are available in git master.
