### ISSUE TITLE
IBus blocks shortcuts with letter keys in Chromium

### ISSUE THREAD

**Issue by minhducsun2002** [ibus/ibus#2073]
- _Which distribution and version?_
```
$ cat /etc/issue
Debian GNU/Linux buster/sid /n /l
```

- _Which desktop environment and version?_
```
$ apt policy xfce4
xfce4:
  Installed: 4.12.5
```

- _Which session type?_
```
$ echo $XDG_SESSION_TYPE 
x11
```

- _Which application and version?_
```
$ apt policy chromium 
chromium:
  Installed: 72.0.3626.7-4
```

- _IBus version?_
```
$ ibus version
IBus 1.5.19
```

- _Issue description :_
Chromium shortcuts with letter keys intercepted by IBus

- _Steps to reproduce:_
1. Fire up Chromium and open a random website with a text field
2. Set focus on the text field or the Omnibox
3. Press a Chromium shortcut that have a letter key, be it Ctrl+N, Ctrl+Shift+I, or Ctrl+Shift+M. It won't work. However, shortcuts without a letter like Ctrl+Tab or Ctrl+PageDown/PageUp works normally.

- _Can you reproduce your problem when you restart ibus-daemon?_

  - Yes. Identical reproduction process.

- _Do you see any errors when you run ibus-daemon with the verbose option?_
```

(ibus-ui-gtk3:29687): IBUS-WARNING **: 09:38:02.652: panel.vala:255: If you launch KDE5 on xterm, export XDG_CURRENT_DESKTOP=KDE before launch KDE5.

(ibus-ui-gtk3:29687): IBUS-WARNING **: 09:38:02.822: ibus_bus_call_sync: org.freedesktop.DBus.Properties.Get: GDBus.Error:org.freedesktop.DBus.Error.Failed: No global engine.

(ibus-ui-gtk3:29687): Gdk-CRITICAL **: 09:38:02.877: gdk_window_thaw_toplevel_updates: assertion 'window->update_and_descendants_freeze_count > 0' failed
```

- _Can you reproduce your problem with a new user account instead of the current your account?_

  - Yes. Identical reproduction process.

**Comment by fujiwarat** [comment]
I cannot reproduce your problem with chrome. Ctrl+N, Ctrl+Shift+I, or Ctrl+Shift+M works fine. But I don't have chromium.
Can you try both chrome and chromium?

**Comment by minhducsun2002** [comment]
Yes. Same problem.

**Comment by minhducsun2002** [comment]
About IBus engine :
```
$ ibus engine
xkb:us::eng
```

Forgot to mention, I'm using Chromium 72.
```
$ apt policy chromium
chromium:
  Installed: 72.0.3626.7-4
  Candidate: 72.0.3626.7-4
  Version table:
 *** 72.0.3626.7-4 500
        500 http://http.us.debian.org/debian testing/main amd64 Packages
        500 http://deb.debian.org/debian sid/main amd64 Packages
        500 http://http.debian.net/debian unstable/main amd64 Packages
        100 /var/lib/dpkg/status
     71.0.3578.80-1~deb9u1 500
        500 http://security.debian.org/debian-security stretch/updates/main amd64 Packages
     69.0.3497.92-1~deb9u1 500
        500 http://ftp.debian.org/debian stable/main amd64 Packages
        500 http://deb.debian.org/debian stretch/main amd64 Packages
```

It's not limited to the Omnibox (yeah you got it right), but any text field being focused will block the shortcuts.

**Comment by fujiwarat** [comment]
I don't think `xkb:us::eng` engine binds Ctrl-n and Ctrl-Shift-l.

Can you reproduce your problem with gtk-im-context-simple besides ibus?

% env GTK_IM_MODULE=gtk-im-context-simple /opt/google/chrome/chrome

**Comment by minhducsun2002** [comment]
`$ GTK_IM_MODULE=gtk-im-context-simple chromium` does allow shortcuts **as normal** with IBus enabled.

**Comment by minhducsun2002** [comment]
```
$ nano a.c
$ gcc -o a a.c `pkg-config --cflags --libs gtk+-3.0` 
$ ./a 
mask c
```
You expect `mask c` or `c`?

**Comment by fujiwarat** [comment]
`mask c` is expected by me and probably I have no idea why you have the problem.

When you type Ctrl-n with ibus, what does happen in the text entry?
How about gedit and firefox?
Do you have special environment variables? `env | grep -i ibus`

**Comment by minhducsun2002** [comment]
```
$ env | grep -i ibus
QT_IM_MODULE=ibus
XMODIFIERS=@im=ibus
```

About `gedit` : Sorry, I don't use it.
About Firefox : Well, things go normal.

When I type Ctrl+N with IBus enabled, nothing happens. As if nothing were typed.

**Comment by fujiwarat** [comment]
> When I type Ctrl+N with IBus enabled, nothing happens. As if nothing were typed.

OK, I see.

My understanding is you can reproduce your problem only with chrome and chromium.
Since I don't have chromium, I'd ask the result of `strace /opt/google/chrome/chrome |& grep immodule` after you install strace.

Can you reproduce your problem with `env GTK_IM_MODULE=ibus  /opt/google/chrome/chrome` ?

**Comment by minhducsun2002** [comment]
`env GTK_IM_MODULE=ibus /opt/google/chrome/chrome` doesn't show the problem. _Because Chrome was on 71, and Chromium was 72._

```
$ strace /opt/google/chrome/chrome |& grep immodule 
openat(AT_FDCWD, "/usr/lib/x86_64-linux-gnu/gtk-3.0/3.0.0/immodules.cache", O_RDONLY) = 99
stat("/usr/lib/x86_64-linux-gnu/gtk-3.0/3.0.0/immodules/im-xim.so", {st_mode=S_IFREG|0644, st_size=35624, ...}) = 0
openat(AT_FDCWD, "/usr/lib/x86_64-linux-gnu/gtk-3.0/3.0.0/immodules/im-xim.so", O_RDONLY|O_CLOEXEC) = 99
```

About `strace`, the problem persists.

**Comment by minhducsun2002** [comment]
Anyway, setting `GTK_IM_MODULE=ibus` then launch Chromium kills the problem.

**Comment by fujiwarat** [comment]
And then your problem is caused bye xim but not ibus.

**Comment by minhducsun2002** [comment]
Problem arises again : IBus will not pick up any keystrokes and instead forward everything to Chromium if `GTK_IM_MODULE=ibus` is used, virtually rendering IBus itself useless.

**Comment by minhducsun2002** [comment]
> My solution is therefore to disable ibus and live without Unicode input.

I had to try Google Input Tools. :(

Also, thanks for pointing out that

> This same version of Chrome worked fine with ibus 1.5.14-3 last week

because I couldn't know which version to roll things back to. I upgrade very often (maybe even daily), thus things break frequently, and I couldn't find a way to restore the old configuration.

**Comment by fujiwarat** [comment]
I'm thinking it would be your setting failure since I cannot reproduce your issue and I mind to spend my time for this.

It would be good to check `env GTK_IM_MODULE=ibus strace  /opt/google/chrome/chrome |& grep immodule`.

**Comment by vphantom** [comment]
@minhducsun2002 FYI I could not disable ibus after all, because that crippled my French input (which was fine without ibus before my Debian upgrade from Stretch to Buster).  i.e. "`a tr`es ^etre" instead of "à très être"

@fujiwarat Will run that trace soon, however I can already tell you that ibus is in use in Chrome in some form because I can use CTRL-SHIFT-U and CTRL-SHIFT-E for Unicode and Emoji respectively, and because its French input behavior and shortcut behavior changes with ibus running vs not.

**Comment by minhducsun2002** [comment]
@vphantom I migrated to Google Input Tools. Thankfully, I don't write Vietnamese comments during coding, so only having the ability to type `vi-VN` in browser is enough.

However Google's solution breaks when it comes to pages that process your keystrokes, like Wikia's Fandom editing page or some programming sites that uses CodeMirror.

**Comment by fujiwarat** [comment]
>  because I can use CTRL-SHIFT-U and CTRL-SHIFT-E

It's not my question but I asked if your problem still can be observed with  the above strace.

**Comment by vphantom** [comment]
@fujiwarat I found a way to run this test without closing my 20-something open tabs. ;)

```text
$ mkdir testchrome
$ env GTK_IM_MODULE=ibus strace google-chrome --user-data-dir=./testchrome/ |& grep immodule
openat(AT_FDCWD, "/usr/lib/x86_64-linux-gnu/gtk-3.0/3.0.0/immodules.cache", O_RDONLY) = 113
writev(35, [{iov_base="\22\0\20\0\16\0\300\5[\1\0\0L\1\0\0\10\0\0\0(\0\0\0immodule"..., iov_len=128}, {iov_base=NULL, iov_len=0}, {iov_base="", iov_len=0}], 3) = 128
writev(35, [{iov_base="\22\0\r\0\16\0\300\5[\1\0\0L\1\0\0\10\0\0\0\33\0\0\0immodule"..., iov_len=104}, {iov_base=NULL, iov_len=0}, {iov_base="", iov_len=0}], 3) = 104
[…]
```

CTRL-SHIFT-U was available, but not CTRL-SHIFT-E so I suspect that someone other than ibus is handling CTRL-SHIFT-U.  French accents still worked, and crucially, CTRL-T did open a new tab even when an input field is in focus.  _However,_ I should note that the variable was already defined in my shell:

```text
$ echo $GTK_IM_MODULE
ibus
```

Next, I forcibly deleted `GTK_IM_MODULE` and traced Chrome again, but got the same results.  Therefore, I suspect that the change of behavior is not triggered by the content or absence of `$GTK_IM_MODULE`.  It must be some other aspect of how Chrome is invoked by my WM vs shell.

I modified the `.desktop` file to get a trace using the test directory and I could finally duplicate my issue: CTRL-T no longer works, CTRL-SHIFT-E appeared and the trace differs: now it also opens `im-xim.so`.

```text
$ grep imm chrometrace.txt
openat(AT_FDCWD, "/usr/lib/x86_64-linux-gnu/gtk-3.0/3.0.0/immodules.cache", O_RDONLY) = 78
stat("/usr/lib/x86_64-linux-gnu/gtk-3.0/3.0.0/immodules/im-xim.so", {st_mode=S_IFREG|0644, st_size=34736, ...}) = 0
openat(AT_FDCWD, "/usr/lib/x86_64-linux-gnu/gtk-3.0/3.0.0/immodules/im-xim.so", O_RDONLY|O_CLOEXEC) = 78
```

So, since Google Chrome didn't change during my upgrade, but that both Gtk and ibus changed, it seems to me that one of the two is the culprit for this regression.  I don't really understand what's going on however, so this is as far as I can go in this round.

What do you think?

**Comment by vphantom** [comment]
Bingo!

```text
titanium:/usr/lib/x86_64-linux-gnu# grep ibus gtk-2.0/2.10.0/immodules.cache
titanium:/usr/lib/x86_64-linux-gnu# grep ibus gtk-3.0/3.0.0/immodules.cache
titanium:/usr/lib/x86_64-linux-gnu# find -name im-ibus.so
titanium:/usr/lib/x86_64-linux-gnu#
```

Files `im-ibus.so` in those locations would be provided by packages `ibus-gtk` and `ibus-gtk3`.  Package `ibus` recommends `ibus-gtk3` but it is not installed.

Now with that package freshly installed, my window manager still launches Chrome such that `im-xim.so` is loaded and Chrome input is buggy.  However if I tweak the desktop file's `Exec` line to define `GTK_IM_MODULE=ibus`, then strace shows that `im-ibus.so` is loaded and Chrome behaves correctly.

Not sure why I need to define that variable explicitly, but I can definitely live with that. :smiley: 

The morale of the story seems to be that I lost `ibus-gtk3` in my Debian dist-upgrade process, and that XFCE doesn't define `GTK_IM_MODULE`, but probably used to before.

Thank you very much for your advice and patience.

**Comment by minhducsun2002** [comment]
@vphantom In short, install `ibus-gtk3`, then `GTK_IM_MODULE=ibus`?

**Comment by fujiwarat** [comment]
That's why I had no motivation about this issue.
I guess the distro provides the IM framework setting tool and you didn't follow it. Normally you don't have to export GTK_IM_MODULE by manual and ibus-gtk3 should be installed with ibus.

**Comment by minhducsun2002** [comment]
Okay, I guess a report about this should be forwarded to Debian IBus maintainers.

Thank you again.

**Comment by vphantom** [comment]
@minhducsun2002 Not for my situation: I had disabled automatic installation of recommendations in Apt because of the noise (lots of `*-doc` packages I don't want, etc.).  It's fine normally, but I should've enabled it during my `dist-upgrade` process to catch this kind of thing.

**Comment by minhducsun2002** [comment]
@vphantom Well, actually, you don't need to. Because doing so merely make all "recommended" things no longer "recommended", but rather obligated. It's up to the package's maintainers to do those things, not you.

However, if you so choose... :smile:

**Comment by vphantom** [comment]
No no, it's actually somewhat common for people to want to save disk space by disabling recommended packages and keeping an eye on recommendations manually, because unfortunately package managers tend to be overzealous with recommendations vs suggestions (i.e. documentation for run-time library packages should not be recommendations, but they usually are).

See `apt --no-install-recommends` and the associated `apt::install-recommends "false"`.

(That said, I realize today that I _do_  have recommendations enabled on my current system, so I have no idea why `ibus-gtk3` was missing.  I still blame the upgrade process; those are always messy.)
