### ISSUE TITLE
如何关闭ibus在中文模式下输入英文，输入 v 的功能？，感觉这个对自己没啥用，还碍事

### ISSUE THREAD

**Issue by heyizhang** [ibus/ibus#2149]
Please fill in the following items if you don't know the root cause.

Which distribution and version?: 
(E.g. Fedora 27. Check /etc/fedora-release)

Which desktop environment and version?: 
(E.g. GNOME 3.24. Check $XDG_CURRENT_DESKTOP and your ISO image.)

Which session type?: 
(X11 or Wayland. Check $XDG_SESSION_TYPE)

Which application and version?: 
(E.g. gedit 3.24, leafpad, kate, xterm)

IBus version?: 
(Run `ibus version`)

Issue description:

Steps to reproduce:
1. 
1. 
1. 
1. 

Can you reproduce your problem when you restart ibus-daemon? (yes / no): 
(Run `ibus exit` and `ibus-daemon --xim &`)

Do you see any errors when you run ibus-daemon with the verbose option?:
(Run `ibus-daemon --xim --verbose &` and look at the output when you encounter your problem.)

Can you reproduce your problem with a new user account instead of the current your account? (yes / no):

**Comment by fujiwarat** [comment]
Which ibus engine do you use? You can check it with `ibus engine` command.
My understanding is you're asking to enable English mode in Pinyin and I think you can type Shift key to toggle English and Chinese in Pinyin.
I don't know why you indicate 'v' and ask to fill the steps to reproduce if your problem is not resolved.

**Comment by heyizhang** [comment]
Got it ! Thank you very much !
