### ISSUE TITLE
There is no persian input method

### ISSUE THREAD

**Issue by imto1** [ibus/ibus#2179]
Which distribution and version?: 
Ubuntu 19.10

Which desktop environment and version?: 
KDE Plasma 5

Which session type?: 
X11

Which application and version?: 
desktop environment

IBus version?: 
1.5.21

Issue description:
**There is no Persian layout in input methods.**

**Comment by mike-fabian** [comment]
Yes, it indeed seems to be missing in /usr/share/ibus/component/simple.xml

I think it should be added.

**Comment by imto1** [comment]
> 
> 
> Yes, it indeed seems to be missing in /usr/share/ibus/component/simple.xml
> 
> I think it should be added.

Can i do it myself? Or it needs to be fixed by developers?

**Comment by mike-fabian** [comment]
> > Yes, it indeed seems to be missing in /usr/share/ibus/component/simple.xml
> > I think it should be added.
> 
> Can i do it myself? Or it needs to be fixed by developers?

You can do it yourself by changing /usr/share/ibus/component/simple.xml as follows:

```
$ diff  -u /usr/share/ibus/component/simple.xml~ /usr/share/ibus/component/simple.xml
--- /usr/share/ibus/component/simple.xml~       2020-01-16 10:04:18.121872951 +0100
+++ /usr/share/ibus/component/simple.xml        2020-02-04 11:32:44.567531693 +0100
@@ -786,5 +786,16 @@
                         <icon>ibus-keyboard</icon>
                        <rank>99</rank>
                </engine>
+               <engine>
+                       <name>xkb:ir::fas</name>
+                       <language>fa</language>
+                       <license>GPL</license>
+                       <author>Peng Huang &lt;shawn.p.huang@gmail.com&gt;</author>
+                       <layout>ir</layout>
+                       <longname>Persian layout</longname>
+                       <description>Persian layout</description>
+                        <icon>ibus-keyboard</icon>
+                       <rank>99</rank>
+               </engine>
        </engines>
 </component>
```

I do that regularly to add my own keyboard layout.

But the next update of ibus will overwrite that file again and you will have to do it again.
After each update of ibus, I always have to add my own special keyboard layout back into simple.xml.

So as a permanent fix, the ibus developers should add that layout to simple.xml.

But until then, I think it is probably very useful for you to add it yourself.

**Comment by imto1** [comment]
Thanks a lot!
I'll try it and let you know the result.

**Comment by imto1** [comment]
> > > Yes, it indeed seems to be missing in /usr/share/ibus/component/simple.xml
> > > I think it should be added.
> > 
> > 
> > Can i do it myself? Or it needs to be fixed by developers?
> 
> You can do it yourself by changing /usr/share/ibus/component/simple.xml as follows:
> 
> ```
> $ diff  -u /usr/share/ibus/component/simple.xml~ /usr/share/ibus/component/simple.xml
> --- /usr/share/ibus/component/simple.xml~       2020-01-16 10:04:18.121872951 +0100
> +++ /usr/share/ibus/component/simple.xml        2020-02-04 11:32:44.567531693 +0100
> @@ -786,5 +786,16 @@
>                          <icon>ibus-keyboard</icon>
>                         <rank>99</rank>
>                 </engine>
> +               <engine>
> +                       <name>xkb:ir::fas</name>
> +                       <language>fa</language>
> +                       <license>GPL</license>
> +                       <author>Peng Huang &lt;shawn.p.huang@gmail.com&gt;</author>
> +                       <layout>ir</layout>
> +                       <longname>Persian layout</longname>
> +                       <description>Persian layout</description>
> +                        <icon>ibus-keyboard</icon>
> +                       <rank>99</rank>
> +               </engine>
>         </engines>
>  </component>
> ```
> 
> I do that regularly to add my own keyboard layout.
> 
> But the next update of ibus will overwrite that file again and you will have to do it again.
> After each update of ibus, I always have to add my own special keyboard layout back into simple.xml.
> 
> So as a permanent fix, the ibus developers should add that layout to simple.xml.
> 
> But until then, I think it is probably very useful for you to add it yourself.

I've done it, but ibus crashed and don't relaunch even when i removed those lines I've added before!
and on ibus preferences i can't see any input method. I don't know what's went wrong!

**Comment by imto1** [comment]
> I've done it, but ibus crashed and don't relaunch even when i removed those lines I've added before!
> and on ibus preferences i can't see any input method. I don't know what's went wrong!

I've purged and re installed ibus and the problem is solved. Also added Persian layout!

**Comment by mike-fabian** [comment]
Good, so the temporary fix  is working for you. 

Now this should be added to simple.xml by the ibus developers  so it doesn't get lost when updating ibus.

By the way, for what language are you using ibus? For Persian? And which ibus engine are you using?

**Comment by imto1** [comment]
> Good, so the temporary fix is working for you.
> 
> Now this should be added to simple.xml by the ibus developers so it doesn't get lost when updating ibus.
> 
> By the way, for what language are you using ibus? For Persian? And which ibus engine are you using?

Yes i'm persian.
My default Desktop environment was Gnome3 and I've decided to test KDE plasma. I never used ibus until KDE installed and honestly i prefer previous input method. I was able to add persian with your help, but whenever my layout is in persian, keyboard shortcuts aren't work.

**Comment by mike-fabian** [comment]
So if I understand you correctly, you need two keyboard layouts, Persian and another one
(maybe US English?) to use for keyboard shortcuts, right?

You say you prefer the previous input method. What was that? Do you mean that in Gnome 3 you had 2 keyboard layouts, Persian and English? Or was it something else?

**Comment by imto1** [comment]
> 
> 
> So if I understand you correctly, you need two keyboard layouts, Persian and another one
> (maybe US English?) to use for keyboard shortcuts, right?
> 
> You say you prefer the previous input method. What was that? Do you mean that in Gnome 3 you had 2 keyboard layouts, Persian and English? Or was it something else?

I've installed ubuntu 19.10 with gnome 3 desktop. Then I've decided to test KDE Plasma and installed KDE. in gnome i have my two keyboard layouts. Both US and Persian works fine. when I set my default Desktop environment to KDE it switched keyboard input method to ibus automatically. last night when i removed ibus, System switched to my previous keyboard and input methods. but i installed ibus again.
Now, when i compare these two input methods, i think gnome input method is better than ibus. With respect to ibus developers ;)

**Comment by mike-fabian** [comment]
> > So if I understand you correctly, you need two keyboard layouts, Persian and another one
> > (maybe US English?) to use for keyboard shortcuts, right?
> > You say you prefer the previous input method. What was that? Do you mean that in Gnome 3 you had 2 keyboard layouts, Persian and English? Or was it something else?
> 
> I've installed ubuntu 19.10 with gnome 3 desktop. Then I've decided to test KDE Plasma and installed KDE. in gnome i have my two keyboard layouts. Both US and Persian works fine. when I set my default Desktop environment to KDE it switched keyboard input method to ibus automatically. last night when i removed ibus, System switched to my previous keyboard and input methods. but i installed ibus again.
> Now, when i compare these two input methods, i think gnome input method is better than ibus. With respect to ibus developers ;)

On recent Gnome, ibus is integrated. So you were probably using ibus in Gnome without knowing it.

The setup of ibus in Gnome looks different than in other desktops because ibus is integrated in Gnome. Therefore, you see the "ibus-setup" tool
where you could not find the Persian keyboard layout only when you did not use Gnome.

**Comment by mike-fabian** [comment]
Screenshot of a Gnome desktop.

![Screenshot](https://user-images.githubusercontent.com/2330175/73847489-ab698d80-4826-11ea-8bba-c56942ef9960.png)

In the terminal in the screenshot you see the output of "ps aux | grep ibus" which confirms that ibus is running.

**Comment by mike-fabian** [comment]
By the way, the above screenshot shows the "Persian (with Persian keypad)" layout.
That is the only variant of the Persian keyboard layout offered by the setup in Gnome.

If you want that variant when using ibus for example in KDE, you need to add one extra line to /usr/share/ibus/component/simple.xml:

```
$ diff -u simple.xml~ simple.xml
--- simple.xml~ 2020-02-04 11:32:44.567531693 +0100
+++ simple.xml  2020-02-05 14:54:44.011101664 +0100
@@ -792,6 +792,7 @@
                        <license>GPL</license>
                        <author>Peng Huang &lt;shawn.p.huang@gmail.com&gt;</author>
                        <layout>ir</layout>
+                       <layout_variant>pes_keypad</layout_variant>
                        <longname>Persian layout</longname>
                        <description>Persian layout</description>
                         <icon>ibus-keyboard</icon>
```

**Comment by imto1** [comment]
Hmm!
I agree with you!
I'm OK with Persian layout. But the problem is keyboard shortcuts(like ctrl+c, ctrl+v) that not work when input method is in Persian.
Is there any workaround for it?

**Comment by mike-fabian** [comment]
You mean Ctrl+c to copy and Ctrl+v to paste?
I just tried that in Gnome setup as in the above screenshot, and it worked, no matter whether I selected the English or the Persian keyboard layout. I tried it in "gedit".

**Comment by imto1** [comment]
> 
> 
> You mean Ctrl+c to copy and Ctrl+v to paste?
> I just tried that in Gnome setup as in the above screenshot, and it worked, no matter whether I selected the English or the Persian keyboard layout. I tried it in "gedit".

Yes. it works fine for me too when i was on gnome. I have this problem on KDE.

**Comment by mike-fabian** [comment]
I think I can reproduce that problem. Trying to find out what is going on there ...⏳

**Comment by mike-fabian** [comment]
Complicated. This is a related bug: 
https://bugs.launchpad.net/unity/+bug/1226962

**Comment by mike-fabian** [comment]
A workaround you can use when using KDE: 

![Screenshot](https://user-images.githubusercontent.com/2330175/73867793-8df8eb80-4847-11ea-9f8d-f1de7b03e8a4.png)

I.e. don’t use ibus to switch the keyboard layouts, use the KDE Keyboard layout switcher instead shown in this screenshot. 
Add your English and Persian layouts there. Note that the Persian layout has the label "ir" in the KDE keyboard layout switcher, not "fa" as in ibus and Gnome. But it is the same layout. 
If you use this to then Control+C and Control+V work even when  using the "ir" layout.

KDE seems to do similar magic to Gnome there.

The problem is that c on the Persian layout gives ز and v gives ر . 
So typing Control-c on the Persian layout doesn’t actually produce Control-c but Control-ز 
But Gnome and KDE are trying to help out and fix this by interpreting Control+something in the English layout if possible.

**Comment by imto1** [comment]
> A workaround you can use when using KDE:
> 
> ![Screenshot](https://user-images.githubusercontent.com/2330175/73867793-8df8eb80-4847-11ea-9f8d-f1de7b03e8a4.png)
> 
> I.e. don’t use ibus to switch the keyboard layouts, use the KDE Keyboard layout switcher instead shown in this screenshot.
> Add your English and Persian layouts there. Note that the Persian layout has the label "ir" in the KDE keyboard layout switcher, not "fa" as in ibus and Gnome. But it is the same layout.
> If you use this to then Control+C and Control+V work even when using the "ir" layout.
> 
> KDE seems to do similar magic to Gnome there.
> 
> The problem is that c on the Persian layout gives ز and v gives ر .
> So typing Control-c on the Persian layout doesn’t actually produce Control-c but Control-ز
> But Gnome and KDE are trying to help out and fix this by interpreting Control+something in the English layout if possible.

Yes it is what I've mentioned before as "my previous keyboard"!
currently I've removed ibus and its dependencies:
`sudo apt purge ibus
sudo apt autoremove`
and now using the keyboard on your screenshot and it works fine.

**Comment by imto1** [comment]
Why do we need to use ibus, when the KDE and Gnome input methods do this already?

**Comment by mike-fabian** [comment]
If you need only "simple" keyboard layouts, then you don’t really need ibus.

The main use case of ibus is for typing stuff you *cannot* do with simple keyboard layouts.
For example, if you type Japanese or Chinese. There are thousands of characters and it would be very impractical to  have a keyboard with thousands of characters. So the most common way to type Japanese is to type Latin Alphabet letters on a normal keyboard and get that translated to Japanese.

For example, if you want to type the word for bird in Japanese you can type "tori" in Latin alphabet using ibus-anthy and you get a combobox  showing 鳥, 鶏, 酉, ...  and some others (because the result is often not unique). Then you select the one you want, which in this example is 鳥 (bird).

Sometimes input using transliteration can be useful even for languages using alphabets.
For example when typing Hindi, one could use a keyboard layout which has the characters.
Or one could use a keyboard layout which has only Latin characters and type the Latin
transliteration. Then you can type "namaste" in Latin and get नमस्ते as the result (which means "hello" in Hindi).

Or maybe one wants to type certain mathematical symbols or emoji conveniently, there are ibus-input methods useful for that as well.

I develop an ibus input method called ibus-typing-booster which is for typing words only partially and then selecting an appropriate completion, like you are probably used from your cellphone. It learns from user input and if you often type similar stuff then it is often enough to type only a few letters and then select a long word from a suggestion list instead of typing the complete word. That can save a lot of keystrokes.

http://mike-fabian.github.io/ibus-typing-booster/documentation.html

Some examples:

http://mike-fabian.github.io/ibus-typing-booster/documentation.html#spanish-english
http://mike-fabian.github.io/ibus-typing-booster/documentation.html#emoji-input
http://mike-fabian.github.io/ibus-typing-booster/documentation.html#unicode-symbols

You could use ibus-typing-booster for Persian for word completion, although if you continue to use KDE you will probably not like it because it forces you to use ibus and they you have the Control+c
not working problem again. But when using Gnome, this works perfectly fine and doesn't disturb 
shortcuts like Control+c at all because Gnome does this magic nicely even though it always uses ibus. 

Another case where one might want  use ibus is when one uses keyboard layouts with a lot of dead keys or uses compose sequences a lot. Using this is possible with plain X11 keyboard layouts but the compose support in ibus has fewer limitations and is easier to use.

**Comment by mike-fabian** [comment]
https://github.com/sfischer13/m17n-fa-post

Here somebody wrote a transliteration input method for Persian. 

This would be usable with ibus-m17n and also with ibus-typing-booster.

So in summary, using ibus is good if one wants to do fancy stuff which is more they just typing one key and getting one letter as a result. 

If all one wants is that one key produces one letter, then a traditional keyboard layout is enough.

**Comment by mike-fabian** [comment]
It still makes sense to add the Persian layout to /usr/share/ibus/component/simple.xml
even if you don’t need that, I think it should be there.

**Comment by imto1** [comment]
> 
> 
> It still makes sense to add the Persian layout to /usr/share/ibus/component/simple.xml
> even if you don’t need that, I think it should be there.


Thank you so much!
Your answers was very helpful to me. I've installed Arch Linux last night and I'm about to install KDE plasma as my default desktop.
I'm sure this information will be useful!
Thank you again.

**Comment by imto1** [comment]
@Developers
My problem is solved. It's your turn to fix it in source code ^_^

**Comment by fujiwarat** [comment]
I think your problem is caused by kimpanel. Killing kimpanel and use the ibus panel can resolve the issue because ibus panel uses the combined keymaps.
