### ISSUE TITLE
候选显示延迟

### ISSUE THREAD

**Issue by yueduz** [ibus/ibus#2236]
一个小建议。在我们快速打字的时候根本看不清候选，当我们要看候选时我们会停止键入。所以，可以对候选显示做一个延迟，在快速键入的时候不显示候选栏，停止键入一断时间后再显示候选。

**Comment by fujiwarat** [comment]
You don't use the bug template but you just described the candidate window is delayed if you type quickly so I don't get your problem with detail.
Probably I don't reproduce your problem.
Which desktop, which IME do you use? How do you reproduce your issue with step?

**Comment by yueduz** [comment]
我不是这个意思，输入面板没有延迟。我是想要实现延迟功能。就像gnome 切换输入法一样，如果我们快速完成输入法切换，不会有视觉提示，切换速度慢才会有提示

**Comment by fujiwarat** [comment]
It's a GNOME issue and please file it to gnoem-shell. I'm not interested in it a little.
For non-GNOME desktop, I support to disable the switcher popup window when you configure two IBus enignes only and then you could set the value of org.freedesktop.ibus.general switcher-delay-time to -1 likes:
`gsettings set org.freedesktop.ibus.general switcher-delay-time -1`
But it does not work in GNOME desktop because gnome-shell uses the owned switcher popup.
