### ISSUE TITLE
Select language-appropriate font variants in the candidate panel.

### ISSUE THREAD

**Issue by xorgy** [ibus/ibus#2238]
I use Japanese and Taiwanese Mandarin input methods, which have font variants which are sometimes very different. Currently, the candidate panel always shows me the Japanese variant of any 漢字 candidate, so in my case the candidate looks very wrong when I type "直" in Chinese, because of how different these variants are.

In Japanese it's <span lang="ja">直</span>, while in Chinese fonts it's <span lang="zh-TW">直</span>. And there are subtler differences, things like like the styling on the top stroke of 言 (<span lang="ja">言</span>{ja} vs <span lang="zh-TW">言</span>{zh-TW}).

I think it may be possible to automatically select the correct variant by setting the pango language attribute for candidate text based on the engine's advertised language.

**Comment by xorgy** [comment]
This could be considered related to #1670, and it may solve the general case for this without adding more configuration state to iBus.

**Comment by xorgy** [comment]
Could be a matter of setting the `AttrLanguage` on [this Pango.AttrList in CandidateArea](https://github.com/ibus/ibus/blob/35863d81d15e3d3463cd5dafd0473afb193c57e3/ui/gtk3/candidatearea.vala#L117); gonna try that out this weekend.

**Comment by fujiwarat** [comment]
Thank you for the report and patch.

I think Pango can select the proper font from the virtual fonts likes Sans, Monospace. If the code point is same, the font might be prioritized from the current locale.
I think your patch will select different fonts between preedit and output strings in Gedit.

From your reply, you might use non-Pango applications. If you wish to follow the non-Pango application, how about treating your patch as an option setting instead of the default setting?

E.g. Add a new key likes "enable-font-from-engine-lang" in GSettings "org.freedesktop.ibus.panel" schema and show the option in "Advanced" tab in ibus-setup utility and the default value is FALSE.

I may mind any regression bugs if the preedit and output strings choose the different fonts in GTK applications.

**Comment by xorgy** [comment]
That is an interesting point. I would personally be okay with it being behind a configuration flag.

I would tend to think this is the correct behaviour anyhow, even if other applications do not attempt language detection, or don't do it properly. If you were, for example, writing into a `<textarea>` on a page with `lang` set correctly at some level in the document, then the default setting would cause the opposite mismatch of the one you're talking about.

I think with the IM panel selecting a language-appropriate variant, you could make the argument that the characters should be familiar to somebody literate in that language. I think it is not uncommon for users to have no `ja_JP` locale but to have a Japanese input method; in my opinion, showing the correct variant for the language is preferable to always showing the wrong variant for some users, to preserve consistency with broken/misconfigured applications.

On the matter of regressions, I thought of the change of the <kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>u</kbd> behaviour as a regression when it was introduced, and the solution there was to introduce a flag that would default to the “regression”. It seems like the logic here is the other way around: the correct behaviour may be viewed as a regression, so default to the broken behaviour.

With all this being said, I can add a configuration key and a checkbox in ibus-setup (with translations), and if you don't want it on by default right now. I'll have the next decade to bug you about it every year until I get my way. ;+ )

**Comment by fujiwarat** [comment]
> If you were, for example, writing into a <textarea> on a page with lang set correctly at some level in the document,

I think Gedit, Thunderbird, Evolution does not support to insert <textarea> tag in the text view and I'm not sure if the different behavior between the applications and IBus lookup window is useful.

> On the matter of regressions, I thought of the change of the Ctrl+Shift+u behaviour as a regression

Right. However I can imagine the issue only when users type Ctrl-Shift-u and currently I get the negative opinion is relative with the  feeling only.

I think the glyphs with the current locale is still useful instead of the engine's language and if users configure a custom font in ibus-setup, the custom font should effect the duplicate code points.

I played your patch and it looks good with me and now I agree the engine's language can be default and I added the configuration patch over your patch:
https://github.com/fujiwarat/ibus/commits/pango-lang-on-lookup

**Comment by xorgy** [comment]
> I think Gedit, Thunderbird, Evolution does not support to insert <textarea> tag in the text view and I'm not sure if the different behavior between the applications and IBus lookup window is useful.

Sorry for the confusion, that's not what I meant. I meant that if you were typing into a textarea in a web page that selected a language-appropriate font, then it would be jarring.

**Comment by xorgy** [comment]
> I played your patch and it looks good with me and now I agree the engine's language can be default and I added the configuration patch over your patch:
> https://github.com/fujiwarat/ibus/commits/pango-lang-on-lookup

Thank you so much for doing that, I don't think I would've gotten around to that for a while. :+ )
