### ISSUE TITLE
Press the 'shift' key, can't switch between Chinese and English mode in google chrome

### ISSUE THREAD

**Issue by inoton** [ibus/ibus#2241]
Distribution and version:
 CentOS Linux release 8.2.2004 (Core)    
(Fedora 32 x64 and other Linux distributions also have this problem.)

Desktop environment and version: 
GNOME Shell 3.32.2

Session type: 
Wayland

Application and version: 
Google Chrome 84.0.4147.89 (official version) (64-bit)

IBus version: 
IBus 1.5.19

Issue description:
cannot use the 'Shift' key to switch between Chinese and English modes in google chrome browser.
"ibus-table-chinese-wubi-haifeng"  and "ibus-table-chinese-wubi-jidian" 

Can you reproduce your problem when you restart ibus-daemon? (yes / no): 
yes

Any errors when you run ibus-daemon with the verbose option:
No errors.
$ ibus-daemon --xim --verbose &
[1] 13884
$ current session already has an ibus-daemon.

Can you reproduce your problem with a new user account instead of the current your account? (yes / no): 
YES

**Comment by mike-fabian** [comment]
I can reproduce that, all keyboard shortcuts which involve shift don't work, using the right Shift key to switch to pinyin mode doesn't work  either in google-chrome.

It works in firefox.

**Comment by mike-fabian** [comment]
Whether using Gnome-Wayland or Gnome-Xorg doesn’t seem to matter here.

**Comment by waynon** [comment]
I‘m facing the same problem. 
Desktop environment: KDE
Distro: Fedora
When I'm using chrome, I can't switch Chinese and English mode using left shift key.

**Comment by inoton** [comment]
> I can reproduce that, all keyboard shortcuts which involve shift don't work, using the right Shift key to switch to pinyin mode doesn't work either in google-chrome.
> 
> It works in firefox.

yes, 'Ibus wubi' works very well in all applications except Chromiun-based browser.
Thank you for your hard work.

**Comment by llzero54** [comment]
I encountered the same problem with **Google Chrome** and **typora**. My system is **ubutnu20.04**.

**Comment by mike-fabian** [comment]
OK, I investigated a bit and I think I understand what causes the problem. 

In ibus-table, I match the hotkeys on the key release event, not on the key press event.

And when looking at the debug.log, I see that **when using google chrome**, the bit indicating the shift modifier (0x1) is set in "state" only when the shift key is pressed, not when it is released 


Shift key pressed:

```
2020-07-21 20:45:19,427 table.py line 3101 _match_hotkey DEBUG: typed key: val=65505 code=42 state=0x00000001 name='Shift_L' unicode='' shift=True control=False mod1=False mod5=False release=False
```

Shift key released:

```
2020-07-21 20:45:19,486 table.py line 3178 do_process_key_event DEBUG: KeyEvent object: val=65505 code=42 state=0x40000000 name='Shift_L' unicode='' shift=False control=False mod1=False mod5=False release=True
```

And when doing the same using firefox, I see in debug.log when shift is released:

```
2020-07-21 20:27:11,521 table.py line 3101 _match_hotkey DEBUG: typed key: val=65505 code=42 state=0x40000001 name='Shift_L' unicode='' shift=True control=False mod1=False mod5=False release=True
```

So here the bit is set when the shift key is released, therefore it works.

I don’t know why this happens when using google-chrome.

But I think I should do the hot-key matching on the key press anyway, not on the key release.

In ibus-typing-booster I do just that and when using ibus-typing-booster I can bind the command to switch the input on or off to just Shift_L and it always seems to work even in google-chrome.

Changing this in ibus-table is a bit complicated. I think I’ll do that by porting the whole way how hotkeys are matched from ibus-typing-booster to ibus-table, this would give the added benefit to make the hotkeys user configurable (as requested in https://github.com/kaio/ibus-table/issues/57).

So it might take a while, but I think I will be able to fix it eventually.

**Comment by inoton** [comment]
Glad to see you've found a solution so quickly.
Thank you so much, Mike.

**Comment by inoton** [comment]
Dear mike-fabian ,
Was the restored version released? 
BTW, how does Centos 8 install it. 
Ignore this message if you arebusy, Thanks!

**Comment by mike-fabian** [comment]
I am working on it, it is going to be a rather big change in the hotkey handling, therefore it is taking a long time.

**Comment by inoton** [comment]
> I am working on it, it is going to be a rather big change in the hotkey handling, therefore it is taking a long time.

Dear Mike,
I realized the follow up would bother you, so deleted that message. It seems you have already read it.
Very patient in waiting for your significant improvements, take your time and thanks for the reply!

**Comment by mike-fabian** [comment]
If you use Fedora 32 you could try the build here:

https://copr.fedorainfracloud.org/coprs/mfabian/ibus-table/

https://download.copr.fedorainfracloud.org/results/mfabian/ibus-table/fedora-32-x86_64/01612003-ibus-table/

**Comment by mike-fabian** [comment]
The above patch should make “Shift_L” work in google-chrome to switch between English and Chinese mode.

The keybindings can also be configured using the command line.

For example when setting:


```
$ dconf write /org/freedesktop/ibus/engine/table/wubi-jidian86/keybindings "{'toggle_input_mode_on_off': <['F12']>}"
```

“F12” is used instead of “Shift_L” to switch between English and Chinese mode.

The default setting would be this:


```
$ dconf write /org/freedesktop/ibus/engine/table/wubi-jidian86/keybindings "{'toggle_input_mode_on_off': <['Shift_L']>}"
```

All commands which are not bound to keys in these user settings keep their defaults.

For example, if one does:

```
$ dconf write /org/freedesktop/ibus/engine/table/wubi-jidian86/keybindings "{'toggle_input_mode_on_off': <['F12']>}"
$ dconf write /org/freedesktop/ibus/engine/table/wubi-jidian86/keybindings "{'toggle_pinyin_mode': <['F11']>}"
```

Then the “toggle_input_mode_on_off” reverts to the default “Shift_L” because the second command line sets only a custom key binding form “toggle_pinyin_mode”, and the custom key binding for “toggle_input_mode_on_off” set in the line before is lost.

If you want to change the defaults for more than one command, you have to do it with one call on the command line, for example like this:

```
$ dconf write /org/freedesktop/ibus/engine/table/wubi-jidian86/keybindings "{'toggle_input_mode_on_off': <['F12']>, 'toggle_pinyin_mode': <['F11']>}"
```

Check the value of the setting:

```
$ dconf dump /org/freedesktop/ibus/engine/table/wubi-jidian86/
[/]
chinesemode=0
keybindings={'toggle_input_mode_on_off': <['F12']>, 'toggle_pinyin_mode': <['F11']>}
```

This works, but it is not convenient at all.

I will rewrite the setup tool so one can do this conveniently with the setup tool.

**Comment by mike-fabian** [comment]
The list of commands where the default keybindings can be changed can be seen in the file

org.freedesktop.ibus.engine.table.gschema.xml 

in:

https://github.com/mike-fabian/ibus-table/commit/2c97c38301b762830cecf3996ad4c5b230b41164

The default key bindings seen in that file may be overridden by a specific table.

For example, the default keybindings to commit the 1st candidate from the gschema.xml are “1” and “KP_1”: 

```
'commit_candidate_1': &lt;['1', 'KP_1']&gt;,
```

For example the source of the latex table has:

```
$ grep SELECT_KEYS ../ibus-table-others/tables/latex.txt 
SELECT_KEYS = F1,F2,F3,F4,F5,F6,F7,F8,F9,F10
```

So when using the latex table, the default keybinding to commit the first candidate is “F1”.
Data for keybindings from a table source has higher priority than the data from the gschema.xml file.

The user settings explained above have highest priority, they can override both the gschema.xml file and the table source.

**Comment by mike-fabian** [comment]
This is the candidate branch for the next release:

https://github.com/mike-fabian/ibus-table/commits/release-candidate-1.11.0

The build for f32 in the copr repo mentioned above:

https://copr.fedorainfracloud.org/coprs/mfabian/ibus-table/

is made from this branch.

**Comment by inoton** [comment]
The instructions are awesome.  appreciated!
Currently using centos .
Use win+space to switch input methods, that's fine too.

**Comment by mike-fabian** [comment]
> Currently using centos .

Would you like me to build a package for testing on centos too?

**Comment by mike-fabian** [comment]
I added a build for centos-stream-x86_64 to copr:

https://copr.fedorainfracloud.org/coprs/mfabian/ibus-table/builds/

https://download.copr.fedorainfracloud.org/results/mfabian/ibus-table/centos-stream-x86_64/01613607-ibus-table/

**Comment by inoton** [comment]
> I added a build for centos-stream-x86_64 to copr:

Hi Mike,
Everything is good after installation, I feel warm and happy at the moment, you're so nice! 👏👏👏

**Comment by mike-fabian** [comment]
ibus-table-1.12.0 now has a new setup tool, now keybindings can be configured with a GUI.

Build for centos-stream-x86_64  of https://github.com/mike-fabian/ibus-table/releases/tag/1.12.0

https://copr.fedorainfracloud.org/coprs/mfabian/ibus-table/build/1636284/
