### ISSUE TITLE
Some GTK+ applications such as Gimp crashes after installing IBus

### ISSUE THREAD

**Issue by weiliang1503** [ibus/ibus#2292]
Please fill in the following items if you don't know the root cause.

Which distribution and version?: 
Arch Linux x86_64

Which desktop environment and version?: 
GNOME 3.38.2

Which session type?: 
Wayland

Which application and version?: 
gimp 2.10.22, xsane 0.999-5

IBus version?: 
IBus 1.5.23

Issue description:
After I installed IBus, gimp and xsane crashes when I am launching them, the log is like this:
```
(gimp:3784): GLib-GObject-WARNING **: 19:34:31.039: specified class size for type 'IBusIMContext' is smaller than the parent type's 'GtkIMContext' class size
malloc(): invalid size (unsorted)
```

```
(xsane:3819): GLib-GObject-WARNING **: 19:35:01.987: specified class size for type 'IBusIMContext' is smaller than the parent type's 'GtkIMContext' class size
malloc(): invalid size (unsorted)
```

Steps to reproduce:
1. Install IBus
2. Run gimp or xsane 

Can you reproduce your problem when you restart ibus-daemon? (yes / no): 
yes

Do you see any errors when you run ibus-daemon with the verbose option?:
no

Can you reproduce your problem with a new user account instead of the current your account? (yes / no): 
I haven't tried.

**Comment by fujiwarat** [comment]
I cannot reproduce your problem.

> (gimp:3784): GLib-GObject-WARNING **: 19:34:31.039: specified class size for type 'IBusIMContext' is smaller than the parent type's 'GtkIMContext' class size malloc(): invalid size (unsorted)

Probably it means your IBus would be built with old GTK2 devel but the installed GTK2 is newer than it.

> Install IBus

I think the IBus packages were built by yourself or distro.
If the IBus was built by yourself, probably you should install the latest GTK2 and GTK2 development packages and build IBus again.
If the IBus was built by distro, you should install the latest GTK2 and if the problem is not resolved, you should ask your distro Arch to build IBus with the latest GTK2.
