### ISSUE TITLE
IBusText has been finalized while it was still owned by gjs, due to #2359

### ISSUE THREAD

**Issue by bdaase** [ibus/ibus#2387]
Please fill in the following items if you don't know the root cause.

Which distribution and version?: 
Fedora 36

Which desktop environment and version?: 
GNOME 42

Which session type?: 
Wayland

Which application and version?: 
gnome-shell

IBus version?: 
1.5.26

Issue description:
The gnome-shell jounral gets spammed with tones of "Object 0x557aa9440850 of type IBusText has been finalized while it was still owned by gjs, this is due to invalid memory management." with the actual object identifier being different every time.

GNOME devs considered it to be fixed by https://github.com/ibus/ibus/pull/2359, but that doesn't seem to be the case.

Steps to reproduce:
1. Start gnome-shell
2. Interact with it a bit

Can you reproduce your problem when you restart ibus-daemon? (yes / no): 

Do you see any errors when you run ibus-daemon with the verbose option?:

Can you reproduce your problem with a new user account instead of the current your account? (yes / no):

**Comment by Emojigit** [comment]
I don't know a lot, but I think a GDB traceback may help the developers, as the 0x* object is absolutely some RAM address.

**Comment by hadess** [comment]
> I don't know a lot, but I think a GDB traceback may help the developers, as the 0x* object is absolutely some RAM address.

This wouldn't help. The object at that address is an object of type `IBusText` which is incorrectly reference counted.

I'm going to hazard a guess that the problem is commit 5a455b1ead5d72483952356ddfe25b9e3b637e6f which used to `unref` objects that were floating, and which now always `unref` the objects were they were floating or not (after sinking them if they were floating). This means that all non-floating objects were having their refcounts reduced by one.

**Comment by fujiwarat** [comment]
Thank you for the report.
I accept there was a wrong process to review #2359.
