### ISSUE TITLE
IBus input method candidate box cannot follow the cursor

### ISSUE THREAD

**Issue by xiaozhangup** [ibus/ibus#2391]
Please fill in the following items if you don't know the root cause.

Which distribution and version?: Ubuntu 22.04
(E.g. Fedora 27. Check /etc/fedora-release)

Which desktop environment and version?: GNOME42
(E.g. GNOME 3.24. Check $XDG_CURRENT_DESKTOP and your ISO image.)

Which session type?: X11
(X11 or Wayland. Check $XDG_SESSION_TYPE)

Which application and version?: 
(E.g. gedit 3.24, leafpad, kate, xterm)

IBus version?: IBus 1.5.26
(Run `ibus version`)

Issue description:
https://bugs.launchpad.net/ubuntu/+source/ibus-libpinyin/+bug/1966552

Steps to reproduce:
1. Not need

Can you reproduce your problem when you restart ibus-daemon? (yes / no): yes
(Run `ibus exit` and `ibus-daemon --xim &`)

Do you see any errors when you run ibus-daemon with the verbose option?: no
(Run `ibus-daemon --xim --verbose &` and look at the output when you encounter your problem.)

Can you reproduce your problem with a new user account instead of the current your account? (yes / no): yes

**Comment by gunnarhj** [comment]
Some key info from the Ubuntu bug:

1. The candidate window is not incorrectly positioned in all applications. Applications mentioned where the issue is present are Microsoft Edge and Onlyoffice. And it happens both on Wayland and Xorg sessions.

1. Set IM environment variables when the issue happens are:
`XMODIFIERS=@im=ibus`
`QT_IM_MODULE=ibus`

1. Setting also `GTK_IM_MODULE=ibus` is said to work around the problem, which makes me suspect that the problem actually lies in some GNOME package such as mutter.

@fujiwarat: I asked the OP to submit this issue, even if I'm not sure that it's actually an ibus issue. At first hand we are seeking your help to spot the root cause.

**Comment by fujiwarat** [comment]
I evaluated Microsoft Edge and it calls `gdk_set_allowed_backends("x11")` and export GDK_BACKEND=*x11* and does not support GdkDisplayWayand because I guess the back compatibility.

> And it happens both on Wayland and Xorg sessions.

I think the problem exits in GNOME Wayland only.

> Setting also GTK_IM_MODULE=ibus is said to work around the problem

It is a workaround for GNOME Wayalnd but a normal way for GNOME Xorg

If you don't set both GTK_IM_MODULE environment variable and gtk-im-module gsettings value, Microsoft Edge sets "xim" by default and you see the problem.

Simce Edge does not support GdkDisplayWayland, exporting GTK_IM_MODULE=wayland causes a SEGV.

I think you could create a shell alias `microsoft-edge 'env GTK_IM_MODULE=ibus microsoft-edge'` for a workaround until it supports Wayland.
