### ISSUE TITLE
Not switching layouts outside of the active textbox

### ISSUE THREAD

**Issue by Ilia01** [ibus/ibus#2563]
Which distribution and version?: 
Any. Both Linux Mint (latest) and ArcoLinux (Arch derivative) recently in my case, but had it before on others

Which desktop environment and version?: 
XFCE, i3 and Cinnamon (idk the versions, not so important here)

Which session type?: 
X11 for sure, not sure if tried on Wayland

Which application and version?: 
Any, system-based problem

IBus version?: 
1.5.26 on this one

Issue description:
The languages switch ONLY when any textbox is active. When I try to switch it out of the textbox it shows up the layouts box and shows it as usual, but no changes really happen. Taking in mind I have another problem not related to ibus (shortcuts only work in latin-script layouts, so I need to change to English to use shortcut) it's almost impossible to use the system that way.

Steps to reproduce:
1. Install and start iBus.
2. Try to do it when no active textbox is present. Profit.

Can you reproduce your problem when you restart ibus-daemon? (yes / no): 
Yes, it's like that always.

Do you see any errors when you run ibus-daemon with the verbose option?:
This is what I have at the start, don't know what it means:

> 
> (ibus-ui-gtk3:52547): IBUS-WARNING **: 01:40:43.041: panel.vala:280: If you launch KDE5 on xterm, export XDG_CURRENT_DESKTOP=KDE before launch KDE5.
> 
> (ibus-ui-gtk3:52547): IBUS-WARNING **: 01:40:43.053: ibus_bus_call_sync: org.freedesktop.DBus.Properties.Get: GDBus.Error:org.freedesktop.DBus.Error.Failed: No global engine.
> 
> (ibus-ui-gtk3:52547): Gdk-CRITICAL **: 01:40:44.057: gdk_window_thaw_toplevel_updates: assertion 'window->update_and_descendants_freeze_count > 0' failed

However no output when trying to switch layouts with no textbox present.

Can you reproduce your problem with a new user account instead of the current your account? (yes / no): 
It's the same for any user on any of the computers I've used.

**Comment by fujiwarat** [comment]
You need to focus on an input context to enable IBus. IBus does not handle XKB only but also input methods and the focus is required to work with input method engines.

**Comment by Ilia01** [comment]
> You need to focus on an input context to enable IBus. IBus does not handle XKB only but also input methods and the focus is required to work with input method engines.

Understood. But is there ANY workaround about it? It's just not possible to use the computer this way. I don't know so much about technical side, so I need help with it, but I do really need to make it work somehow.

**Comment by fujiwarat** [comment]
> so I need help with it, but I do really need to make it work somehow.

You don't explain why it helps you at all.

**Comment by Ilia01** [comment]
> > so I need help with it, but I do really need to make it work somehow.
> 
> You don't explain why it helps you at all.

Because otherwise it's not possible to use computer - any key combination isn't work anymore (for some reason it requires English letters instead of keyboard keys). I cannot switch the layout to use any until I'll open some text box(e.g. notebook) and switch the language there. That's at least weird behavior.

**Comment by Ilia01** [comment]
Nevermind, I found a workaround using another input engine. The only problem is that I cannot use Chinese or Japanese now.

**Comment by fujiwarat** [comment]
You can switch the layout with input focus and you cannot input any characters until you get the focus.

**Comment by Ilia01** [comment]
Correct. And that's exactly the problem - I can switch layout ONLY with input focus, which is not correct behavior

**Comment by fujiwarat** [comment]
You should not input any characters without focus and no need to switch layouts too.

**Comment by mike-fabian** [comment]
> > Now I press Super+a which actually produces a Super+Cyrillic_ef
> 
> That would be another issue. Probably XKB would be better to provide Super keys likes combined layouts ru,us.

Yes, somehow this works magically in Gnome but does not work in other desktops. I don't know how this is done. In Gnome, even if a layout which does not produce ASCII is selected, If some modifier followed by a key is typed (which produces non-ASCII output!) then nevertheless it is checked whether this would have been a shortcut key if the US layout had been active. I really have no idea how this works, but it is very nice and useful for users of keyboard layouts which don't produce ASCII.

> > This works in Gnome, but not in XFCE, i3, Cinnamon ..
> 
> Do not confuse you use GNOME which can handle multiple IMF likes ibus and gtk-im-context. IBus panel handles IBus only with the active input focus.

Maybe it is because of the ibus integration in Gnome that Gnome has more control over this? If you change input methods by using Super+space in Gnome, then the indicator in the panel changes and if one has switched to a new keyboard layout, the layout seems to be active immediately.

But if one tries to switch with Super+space in XFCE while nothing has focus, the indicator in the panel does not change.

For example, in XFCE, `Control+Alt+T` is the shortcut to start a terminal. That works if the `EN` layout is active, but it does not work when the `RU` layout is active.

If `RU` is displayed in the panel and one uses `Super+space` to try to switch to `EN` while nothing has input focus, then the `RU` stays in the panel and does not switch to `EN`.

So if you see `RU` in the panel and nothing has input focus, you cannot use use `Control+Alt+T` to start a terminal and you cannot switch to `EN` with `Super+space` to become able to use the `Control+Alt+T` shortcut. You either have to use the mouse to switch in the panel from `RU` to `EN` or open something with input focus and switch using `Super+space` then.

I think this user is complaining that he

1) needs to switch to English to be able to use keyboard shortcuts containing Latin letters (Gnome can do this without switching to English)

2) Switching to English with the keyboard (`Super+space`) doesn't work when there is no input focus, so it is inconvenient to use keyboard shortcuts in that situation, one either has to use the mouse to switch or first open something which has input focus, switch with `Super+Space`, then use the desired keyboard shortcut.


So Gnome does this much better than other desktops.

I don’t know why and I don’t know whether this could be improved or not.

Maybe it is impossible to make `Super+space` switch the input method and update the panel indicator without input focus in XFCE? It could well be impossible for ibus, I don’t know.

Theoretically XFCE could implement an ibus integration similar to the ibus integration in Gnome, then it would surely be possible. But that would be work for the XFCE developers, not for ibus, I guess.

**Comment by mike-fabian** [comment]
In the situation in this screenshot, nothing has input focus, `Control+Alt+T` does not open a terminal because `RU` is visible in the panel and switching with `Super+space`  to `EN` doesn't work, so one needs to use the mouse or open something with  input focus first, then switch, then use the `Control+Alt+T`:

![Screenshot](https://github.com/ibus/ibus/assets/2330175/145cf225-2d11-4df9-b19a-4b249ccd71ca)

**Comment by Ilia01** [comment]
Correct. And that's exactly the problem - I can switch layout ONLY with input focus, which is not correct behavior

> I think what @Ilia01 wants works when ibus is used in Gnome. See the video below.
> Peek.2023-09-12.16-25.mp4
> 
> I start with the Russian keyboard layout, `ru` is shown in the gnome panel.
> 
> In the page of the gnome control center shown one can see that there is a shortcut:
> 
> "Show all apps" `Super+A`
> 
> (Actually they mean `Super+a` I don’t know why Gnome shows capital letters there, only the lower case ones work)
> 
> Now I press `Super+a` which actually produces a `Super+Cyrillic_ef` because the Russian keyboard is active. Nevertheless, some magic 🧙‍♂️ makes the shortcut work and "Show all apps" is really done. I focus the search entry and type `aaa` and see `ффф` (Three times Cyrillic_ef) which confirms that the Russian keyboard layout is active. So `Super+Cyrillic_ef` was typed, but nevertheless the keyboard shortcut for `Super+a` was executed. Surprising, but nice, i.e. in Gnome one does not even have to switch the keyboard layout in most cases to execute these shorctuts.
> 
> But one can, as I show in the next step:
> 
> I go back to the original screen by typing `Escape` `Escape`.
> 
> Then I use `Super+space` to switch the keyboard layout to `en`. Note that `ru` in the panel changes to `en`, even though nothing had input focus. This works in Gnome, but **not** in XFCE, i3, Cinnamon ...
> 
> To test whether the keyboard layout really changed, I type `Super+a` again. It works and I get `Show all apps` executed.
> 
> I type the `a` key in the search field and now I get `aaa`, **not** `ффф`.
> 
> It is hard to say whether the layout really changed before that search field got focus because the keyboard shortcuts in Gnome seem to work always, no matter whether the keyboard is changed or not.
> 
> But it looks like it changed because the switch between `ru` and `en` can be seen in the panel, even though nothing has input focus.

You've just perfectly described expected behavior. Yes, that is the thing I want to achieve. When I used gnome on fedora - it was perfect in this sense, however I don't like gnome for many another reasons, so what I want is being able to achieve this on any another DE or WM. I don't really know if it's related specifically to input engine or it is some other part of the system - that's why I'm asking more experienced users here. =)

**Comment by Ilia01** [comment]
> Maybe it is because of the ibus integration in Gnome that Gnome has more control over this? If you change input methods by using Super+space in Gnome, then the indicator in the panel changes and if one has switched to a new keyboard layout, the layout seems to be active immediately.


> Maybe it is impossible to make `Super+space` switch the input method and update the panel indicator without input focus in XFCE? It could well be impossible for ibus, I don’t know.

On my second computer (laptop) I have i3 WM instead of any DE. I don't know what I've exactly did (I tried a lot of solutions) and how, but after many hours I've achieved both of those behaviors on Fcitx. Before trying Fcitx I've tried it on iBus (it seems a bit more user-friendly to me), but with no results. So I suppose (but I'm still not sure) that it's possible on input engine's side.

Even though I found a semi-solution for that with Fcitx I couldn't achieve Chinese language on it, it continues to write in English. So I'll not change engine on my primary computer and even on secondary it still needs a solution. So I do hope that anyone knows the answer!

**Comment by Ilia01** [comment]
BTW, have tested it on Cinnamon DE - works the same as on Gnome, both of the things (shortcuts on non-latin layouts and changing layouts without focus) work with iBus selected as an input engine. But on this one for some reason even when I add Chinese layout it switches only between English and Ukrainian. (I know about it switching between the two and that you need to touch shift two time with holding alt down, but it still doesn't work (and it's another thing which is preferable to be able to choose the behavior)).

**Comment by fujiwarat** [comment]
> For example, in XFCE, Control+Alt+T is the shortcut to start a terminal. That works if the EN layout is active, but it does not work when the RU layout is active.

Not sure why you indicate Ctrl-Shift-t and it works with ru,us layout and you could see "xkb-latin-layouts" gsettings key includes "ru". Also Super-space works with "ru,us" layout.

> Maybe it is because of the ibus integration in Gnome that Gnome has more control over this? 

Again IBus handles IBus only.

**Comment by mike-fabian** [comment]
> > For example, in XFCE, Control+Alt+T is the shortcut to start a terminal. That works if the EN layout is active, but it does not work when the RU layout is active.
> 
> Not sure why you indicate Ctrl-Shift-t and it works with ru,us layout and you could see "xkb-latin-layouts" gsettings key includes "ru". Also Super-space works with "ru,us" layout.

Ctrl+Shift+t does indeed work in xfce4-terminal even if Russian keyboard layout is active. Surprising! Maybe the terminal does something special? Ctrl-Shift-t opens a new tab in the terminal, maybe the terminal itself handles this and not XFCE?

 But even when I do `setxkbmap ru,us` in a  terminal in XFCE, the Control+Alt+t shortcut to open a new  terminal window still does not work. With `setxkbmap us` it does work.

> > Maybe it is because of the ibus integration in Gnome that Gnome has more control over this?
> 
> Again IBus handles IBus only.

Yes, maybe it is not the problem of IBus, it could be a problem of XFCE, but I am not sure.

**Comment by fujiwarat** [comment]
> Ctrl+Shift+t does indeed work in xfce4-terminal even if Russian keyboard layout is active. Surprising! Maybe the terminal does something special? Ctrl-Shift-t opens a new tab in the terminal, maybe the terminal itself handles this and not XFCE?

Ah, I mistook Ctrl-Alt-t and Ctrl-Shift-t and I understood your issue now.
Maybe xfce4-session owns the session manager and window manager and I don't know why the issue can happen but I'd like to say it would be a bug in XFCE.
I tried Ctrl-Alt-y with `xev` and I don't see any differences between `us` and `ru,us` layouts.

>>    Again IBus handles IBus only.

> Yes, maybe it is not the problem of IBus, it could be a problem of XFCE, but I am not sure.

If you try Plasma Wayland, IBus shortcut key is enabled on the input context only and any global shortcut keys are no longer supported due to the security issue.
I don't think to implement the old X11 specific and IBus works on the active input context only because he desn't explain why it helps you at all.

Probably the workaround would be to register a script with a user shortcut key into the window manager.
E.g. Run `ibus engine` and get the current engine and get GSettings value of org.freedesktop.ibus.general engines-order and set the next engine.

**Comment by mike-fabian** [comment]
> Probably the workaround would be to register a script with a user shortcut key into the window manager. E.g. Run `ibus engine` and get the current engine and get GSettings value of org.freedesktop.ibus.general engines-order and set the next engine.

Yes, indeed, this works. I tried running a script like the following in XFCE in a terminal:

```
#!/bin/bash

trap "echo Exited.; exit;" SIGHUP SIGINT SIGTERM

while true
do
    echo ru
    ibus engine xkb:ru::rus
    sleep 3
    echo en
    ibus engine xkb:us::eng
    sleep 3
done
```

Even when nothing has input focus, one can see the ibus indicator in the XFCE panel switching between `EN` and `RU` every 3 seconds.

So `ibus engine xkb:us::eng` can switch the input method even when nothing has input focus.

But `Super+space` cannot do that. Why not? What is the difference between `ibus engine ...` and `Super+space`?

**Comment by fujiwarat** [comment]
> But Super+space cannot do that. Why not? What is the difference between ibus engine ... and Super+space?

IBus panel does not support to change ibus engines without focus but not for layouts only.

**Comment by mike-fabian** [comment]
> > But Super+space cannot do that. Why not? What is the difference between ibus engine ... and Super+space?
> 
> IBus panel does not support to change ibus engines without focus but not for layouts only.

But maybe that could be improved? If it can be done by a script calling `ibus engine ...` and one can bind such a script to a key, for example `Super+space`, then it should also be possible for ibus to do this? Or am I misunderstanding something?

**Comment by fujiwarat** [comment]
IBus panel does not support to change ibus engines without focus but not for layouts only. IBus engines are initialized with the focus-in events.

**Comment by jeanclaude-desrosiers** [comment]
I stumbled upon this GitHub issue while looking for a solution.

This allows to toggle between current and previous engines. Just add this code in a bash script:
```bash
ibus engine $(ibus read-config | grep engines-order | cut -d"'" -f4)
```
Then create a custom keyboard shortcut to run the script.

This work-around is probably not ideal, but it allows the tool to do what I want (good enough for me :shrug:)
