### ISSUE TITLE
The GNOME lock screen shortcut key does not work with some input method

### ISSUE THREAD

**Issue by epico** [ibus/ibus#2608]
Which distribution and version?: 
Fedora 39

Which desktop environment and version?: 
GNOME 45

Which session type?: 
Wayland

Which application and version?: 
gedit 45.0

IBus version?: 
IBus 1.5.29-rc2

Issue description:
The input method like ibus-libpinyin or ibus-anthy captures the Super+l shortcut key which locks the GNOME screen. The gnome-shell doesn't lock the screen after press Super+l key.

Steps to reproduce:
1. Login GNOME Wayland, and add some input methods like ibus-libpinyin and ibus-anthy
1. Launch gedit, and switch to use ibus-libpinyin or ibus-anthy
1. Press Super+l key, the screen is not locked

**Comment by epico** [comment]
Sorry, my mistake.

Maybe this is the expected result of ibus-anthy.

I will check the ibus-libpinyin code soon.

**Comment by fujiwarat** [comment]
Thank you for your heads up.
Thinking about this issue again, ibus-anthy ignores `Alt-<ASCII>` in case ibus-anthy does not have the same shortcut keys and also should do `Super--<ASCII>` for the similar case.
https://github.com/fujiwarat/ibus-anthy/commit/9ae92d7

It means the users still can configure the custom shortcut keys with `Super-<ASCII>` in ibus-anthy and it's not an IBus core issue.

And I assume Super-l would not be so important in the Hiragana mode since I have already fixed Super-space issue and it won't be in ibus-anthy 1.5.16
