### ISSUE TITLE
Is there any similar punctuation mapping file like fcitx5(fcitx5/conf/punctuation.conf)?

### ISSUE THREAD

**Issue by seflerZ** [ibus/ibus#2680]
Is there any similar punctunation mapping file like fcitx5(fcitx5/conf/punctuation.conf)? I do not want all puctunation to be full character, like +, =, etcetera.

**Comment by mike-fabian** [comment]
Which ibus input method are you using?

**Comment by seflerZ** [comment]
The ibus-table-wubi comes with Ubuntu by default.

**Comment by mike-fabian** [comment]
The options

Table input punctuation width [half]
Direct input punctuation width [half]

do not do what you want?

See this screenshot of the setup tool:
![Screenshot](https://github.com/user-attachments/assets/3f7e0db7-90c3-429b-8e6a-e7f851e3ea8e)

**Comment by mike-fabian** [comment]
@seflerZ 

With these options, you can choose **all** your punctuation to be half width or **all** your punctuation to be full width.

But maybe you are looking for  more fine grained settings? Like using a full width question mark  `？` but using a half width `+`?

Such  fine grained control is currently not available in ibus-table.

If you want such a feature, please open a feature request for ibus-table here:

https://github.com/mike-fabian/ibus-table/issues

We need to discuss then how exactly this feature should work and how to integrate it into the setup UI.

In any case, this issue is not directly related to ibus, so I am closing this issue here.

If you use wubi, then you use ibus-table, so please an enhancement request there if you need more than what is currently possible.

**Comment by seflerZ** [comment]
@mike-fabian more grained settings needed. I need full width question mark and half width +, because the full width ＋ can not be recongized in most calculation systems. Thank you for your suggestion.

**Comment by mike-fabian** [comment]
So please open an enhancement issue for ibus table and let's discuss how to implement it best.
